#!/usr/bin/env python3
"""
Generates verification-only top-level wrapper modules that connect a design
block to a real TRNG instance for cocotb-based simulation.

These wrappers are NOT part of the design (they exist purely so testbenches
have a self-contained DUT to drive) and are intentionally not committed to
git. The Makefile invokes this script with a block name before compiling for
`run_test`/`run_all`; lint/synth/standalone RTL compilation never call this
and only ever see the real design files.

Usage: python3 gen_top.py <block>
  where <block> is one of: sbox_top, addRoundKey_top, cipher_top
"""
import sys
from pathlib import Path

RTL_DIR = Path(__file__).parent.resolve()

HEADER = """\
// AUTO-GENERATED by gen_top.py -- verification-only wrapper.
// Connects {block} to a real TRNG instance for cocotb simulation.
// This file is not part of the design and is not committed to git.
"""

# All instantiations below use NAMED port connections deliberately: positional
# connections silently misalign (with no compile error) whenever a module's
# port list gains/loses a port, which is exactly what caused sbox.sv's clk/rst_n
# to end up floating after `sbox_cntr`/`fsm_state` were added to its port list.
#
# Reset combining also intentionally uses `ext_rst_n & !rst_trng` (not
# `ext_rst_n | rst_trng`): trng_rst feeds TRNG's active-low reset, so it must
# go low if EITHER the external reset is asserted OR the Sbox is demanding a
# forced reset after a fatal TRNG failure. The `|` form can never let rst_trng
# actually force a reset during normal operation (ext_rst_n=1 dominates).

SBOX_TOP = """\
import type_defs_pkg::*;

module sbox_top(
    // S-box output (SubBytes result)
    output logic [127:0] subBytes,  // 4x4 state matrix (16 bytes total)
    output logic sbox_ready,  // S-box ready for next input
    output logic trng_dead_flag,  // TRNG has encountered fatal error
    output logic sbox_done_pulse,  // single clock cycle pulse when Sbox has computed SubBytes
    output logic rst_trng,  // S-box can reset TRNG if needed
    input logic clk,  // Main clock
    input logic [1:0] sbox_enb_n,  // SBox enable signal
    input logic sampling_clk,  // High-frequency clock for noise source
    input logic ext_rst_n,  // External reset (active low)
    input logic raw_rand_bit,  // Raw random bit from noise source (py model)
    input logic proceed,  // testbench acknowledges sbox_done_pulse so Sbox can advance past SUB_BYTES
    input logic [127:0] sbox_input);  // 128-bit plaintext

    // TRNG to S-box connections
    logic [1679:0] rand_num;  // random data from TRNG
    logic trng_key_valid;  // TRNG: data is valid
    logic trng_rst;  // combined reset driven into TRNG

    assign trng_rst = ext_rst_n & !rst_trng;

    trng TRNG(
        .rand_word(rand_num),
        .trng_key_valid(trng_key_valid),
        .dead_flag(trng_dead_flag),
        .sbox_ready(sbox_ready),
        .raw_rand_bit(raw_rand_bit),
        .sampling_clk(sampling_clk),
        .clk(clk),
        .ext_rst_n(trng_rst));

    sbox Sbox(
        .subBytes(subBytes),
        .sbox_ready(sbox_ready),
        .sbox_done_pulse(sbox_done_pulse),
        .rst_trng(rst_trng),
        .trng_dead_flag(trng_dead_flag),
        .state(sbox_input),
        .rand_num(rand_num),
        .trng_key_valid(trng_key_valid),
        .proceed(proceed),
        .enb_n(sbox_enb_n[1]),
        ._enb_n(sbox_enb_n[0]),
        .rst_n(ext_rst_n),
        .clk(clk));
endmodule
"""

ADDROUNDKEY_TOP = """\
import type_defs_pkg::*;

module addRoundKey_top (
    output state_matrix_t addRoundKeyOut,  // output of addRoundKey
    output logic [1679:0] rand_num,  // random data from TRNG
    output logic ark_done,  // indicates that addRoundKey is done with computation
    output word_t subByte,  // subBytes computed by SBox
    output word_t sbox_state,  // rotated version of generated KEY is sent to SBox as input
    output logic [1:0] sbox_enb_n,  // enable signal which enables or disables only a portion of SBox
    output logic sbox_ready,  // S-box ready for next input
    output logic sbox_done_pulse,  // single clock cycle pulse when Sbox has computed SubBytes
    output logic trng_key_valid,  // TRNG: data is valid
    input logic [255:0] master_key,  // input master KEY
    input state_matrix_t state,  // input state matrix
    input unibble round_num,  // input CIPHER which indicates number of AES rounds
    input logic [1:0] key_size,  // input from CONTROL register specifying the KEY size
    input logic raw_rand_bit,  // raw random bit from noise source
    input logic sampling_clk,  // high frequency independent clock for noise source
    input logic ark_enb_n,  // addRoundKey enable signal
    input logic rst_n, clk);

    logic trng_dead_flag;  // TRNG has encountered fatal error
    logic rst_trng;  // S-box resets TRNG if it encounters a fatal error
    logic trng_rst;  // combined reset driven into TRNG
    // AddRoundKey is the only caller of this Sbox instance, so it can proceed
    // as soon as it has consumed the result -- ark_done directly acknowledges
    // sbox_done_pulse with no separate ack register needed.
    logic sbox_proceed;

    // width adapters: the sbox state/subBytes ports are 128-bit, but the
    // KeyExpansion path only ever uses the low 32 bits (word mode)
    logic [127:0] sbox_state_ext;  // zero-extended sbox input word
    logic [127:0] subBytes_full;  // full-width sbox output; only [31:0] is meaningful here

    assign trng_rst = rst_n & !rst_trng;
    assign sbox_state_ext = {96'd0, sbox_state};
    assign subByte = subBytes_full[31:0];
    assign sbox_proceed = ark_done;

    trng TRNG(
        .rand_word(rand_num),
        .trng_key_valid(trng_key_valid),
        .dead_flag(trng_dead_flag),
        .sbox_ready(sbox_ready),
        .raw_rand_bit(raw_rand_bit),
        .sampling_clk(sampling_clk),
        .clk(clk),
        .ext_rst_n(trng_rst));

    sbox SBox(
        .subBytes(subBytes_full),
        .sbox_ready(sbox_ready),
        .sbox_done_pulse(sbox_done_pulse),
        .rst_trng(rst_trng),
        .trng_dead_flag(trng_dead_flag),
        .state(sbox_state_ext),
        .rand_num(rand_num),
        .trng_key_valid(trng_key_valid),
        .proceed(sbox_proceed),
        .enb_n(sbox_enb_n[1]),
        ._enb_n(sbox_enb_n[0]),
        .rst_n(rst_n),
        .clk(clk));

    addRoundKey AddRoundKey(
        .addRoundKeyOut(addRoundKeyOut),
        .ark_done(ark_done),
        .sbox_state(sbox_state),
        .sbox_enb_n(sbox_enb_n),
        .state(state),
        .master_key(master_key),
        .subByte(subByte),
        .round_num(round_num),
        .key_size(key_size),
        .sbox_done(sbox_done_pulse),
        .enb_n(ark_enb_n),
        .rst_n(rst_n),
        .clk(clk));
endmodule
"""

CIPHER_TOP = """\
import type_defs_pkg::*;

module cipher_top(
    output state_matrix_t cipher_state,  // state matrix that has gone through whole CIPHER algorithm
    output logic [1679:0] rand_num,  // random data from TRNG
    output logic cipher_done,  // becomes high when CIPHER is done computing transformed state
    output logic sbox_ready,  // sbox acknowledges receiption of random words
    output logic trng_key_valid,  // tells S-box that random words are ready
    output logic trng_dead_flag,  // TRNG has encountered fatal error
    input state_matrix_t state,  // input state matrix (plain text)
    input logic [255:0] master_key,  // MASTER KEY required for key expansion
    input logic [1:0] key_size,  // AES KEY size from CONTROL register
    input logic raw_rand_bit,  // raw random bit from noise source
    input logic rst_n, sampling_clk, clk);

    logic rst_trng;  // resets TRNG when health test results in fatal failures
    logic trng_rst;  // combined reset driven into TRNG

    assign trng_rst = rst_n & !rst_trng;

    trng TRNG(
        .rand_word(rand_num),
        .trng_key_valid(trng_key_valid),
        .dead_flag(trng_dead_flag),
        .sbox_ready(sbox_ready),
        .raw_rand_bit(raw_rand_bit),
        .sampling_clk(sampling_clk),
        .clk(clk),
        .ext_rst_n(trng_rst));

    cipher CIPHER(
        .cipher_state(cipher_state),
        .cipher_done(cipher_done),
        .sbox_ready(sbox_ready),
        .rst_trng(rst_trng),
        .state(state),
        .rand_num(rand_num),
        .master_key(master_key),
        .key_size(key_size),
        .trng_key_valid(trng_key_valid),
        .trng_dead_flag(trng_dead_flag),
        .rst_n(rst_n),
        .clk(clk));
endmodule
"""

TEMPLATES = {
    "sbox_top": SBOX_TOP,
    "addRoundKey_top": ADDROUNDKEY_TOP,
    "cipher_top": CIPHER_TOP,
}


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in TEMPLATES:
        valid = ", ".join(sorted(TEMPLATES))
        print(f"Usage: python3 gen_top.py <block>\n  <block> must be one of: {valid}", file=sys.stderr)
        sys.exit(1)

    block = sys.argv[1]
    out_path = RTL_DIR / f"{block}.sv"
    out_path.write_text(HEADER.format(block=block) + "\n" + TEMPLATES[block])
    print(f"Generated '{out_path}'")


if __name__ == "__main__":
    main()
