import numpy as np
from scipy.stats import binom
import math

# configuration
N_RO = 32               # number of parallel ring oscillators
N_INV = 13              # number of inverters per ring oscillator (must be odd)
MEAN_LOW = 275          # ps  - lower bound of per-RO mean delay (process variation)
MEAN_HIGH = 282         # ps  - upper bound of per-RO mean delay (process variation)
SIGMA = 30              # ps  - std-dev of Gaussian jitter (local thermal/flicker noise)
CONSECUTIVE_ERRORS = 3  # number consecutive errors in health tests
SEED = None  
rng = np.random.default_rng(SEED)

# health tests parameters as per IST standard
ALPHA = 0.01           # false positive probability (NIST standard)
H_MIN = 0.9982         # measured min-entropy per bit (your design's measured value)
APT_BIT_WINDOW = 1024  # APT window size (fixed by NIST SP 800-90B for binary sources)
# p = most likely symbol probability, derived from min-entropy
# as per NIST SP 800-90B standard, p = 2^(-H_min)
# This is the probability of the MOST LIKELY symbol.
# For a nearly balanced source (H_min close to 1), p is close to 0.5.
p = 2 ** (-H_MIN)

# 1. RCT threshold calculation
"""
C = 1 + ⌈-log₂(alpha) / Hₘᵢₙ⌉

Where:
  C     = RCT threshold
  alpha = False positive probability (0.01 as per NIST standard)
  Hₘᵢₙ  = Minimum entropy per bit (0.9982 for the design config)
  ⌈...⌉ = Ceiling function (round UP)
"""
RCT_THRESHOLD = 1 + math.ceil(-math.log2(ALPHA) / H_MIN)

# 2. APT threshold calculation
"""
C = 1 + iCDF_Binomial(W, p, 1 - alpha)

where iCDF_Binomial(n, p, q) is the smallest integer C such that:
  P(X <= C) >= q     i.e. the quantile function

Equivalently, find smallest C such that:
  P(X >= C) <= alpha
where X ~ Binomial(W, p)

The +1 shift is explicit in the NIST spec to ensure the inequality
P(X >= C) <= alpha is strictly satisfied
"""
apt_icdf = binom.ppf(1 - ALPHA, APT_BIT_WINDOW, p)
APT_THRESHOLD = int(apt_icdf) + 1

OUTPUT_FILE = "../rtl/ro_param_pkg.sv"

# Each RO gets a unique base mean drawn from [MEAN_LOW, MEAN_HIGH].
# This models inter-oscillator frequency spread due to manufacturing variation.
# On top of that, every individual inverter gets an independent Gaussian
# perturbation (µ=0, σ=SIGMA) — this is the cycle-to-cycle jitter that
# is the actual entropy source.
ro_means = rng.uniform(MEAN_LOW, MEAN_HIGH, size=N_RO)          # shape (N_RO,)
jitter   = rng.normal(0, SIGMA, size=(N_RO, N_INV))             # shape (N_RO, N_INV)
delays   = np.abs(ro_means[:, np.newaxis] + jitter)             # ensure positive ps

# format helpers 
def ps_to_timescale(ps: float) -> str:
    """
    Convert a picosecond value to a `timescale 1ps/1ps compatible integer.
    We round to the nearest integer ps so the value is usable as a
    Verilog delay literal without fractional precision issues.
    """
    return str(int(round(ps)))

# 5x5 Rho Offsets Matrix
rho_matrix = [
  [0,  36,  3,  41,  18],
  [1,  44,  10, 45,  2],
  [62, 6,   43, 15,  61],
  [28, 55,  25, 21,  56],
  [27, 20,  39, 8,   14]
]

# build package string 
lines = []
lines.append("// AUTO-GENERATED by gen_param.py")
lines.append("//")
lines.append(f"// Model parameters:")
lines.append(f"//   N_RO     = {N_RO}")
lines.append(f"//   N_INV    = {N_INV}  (inverters per RO, must be odd)")
lines.append(f"//   Mean     ~ Uniform({MEAN_LOW} ps, {MEAN_HIGH} ps) per RO")
lines.append(f"//   Jitter   ~ Gaussian(mu=0, sigma={SIGMA} ps) per inverter")
lines.append(f"//   RCT Threshold  = {RCT_THRESHOLD}")
lines.append(f"//   APT Bit Window = {APT_BIT_WINDOW}")
lines.append(f"//   APT Threshold  = {APT_THRESHOLD}")
lines.append(f"//   CONSECUTIVE_ERRORS = {CONSECUTIVE_ERRORS}")
lines.append("")
lines.append("`timescale 1ps/1ps")
lines.append("")
lines.append("package ro_delay_pkg;")
lines.append("")
lines.append(f"  // Total number of ring oscillators")
lines.append(f"  localparam int N_RO  = {N_RO};")
lines.append(f"  // Number of inverters in each ring oscillator")
lines.append(f"  localparam int N_INV = {N_INV};")
lines.append(f"  // NIST SP 800-90B Repetition Count Test (RCT) Threshold")
lines.append(f"  localparam int RCT_THRESHOLD = {RCT_THRESHOLD};")
lines.append(f"  // NIST SP 800-90B Adaptive Proportion Test (APT) bit window")
lines.append(f"  localparam int APT_BIT_WINDOW = {APT_BIT_WINDOW};")
lines.append(f"  // NIST SP 800-90B Adaptive Proportion Test (APT) Threshold")
lines.append(f"  localparam int APT_THRESHOLD = {APT_THRESHOLD};")
lines.append(f"  // number consecutive errors in health tests")
lines.append(f"  localparam int CONSECUTIVE_ERRORS = {CONSECUTIVE_ERRORS};")
lines.append("")
lines.append("  // RHO_OFFSETS[row][col] - Fixed rotation constants for Keccak/SHA3")
lines.append("  localparam int RHO_OFFSETS [0:4][0:4] = '{")

for i, row in enumerate(rho_matrix):
  row_vals = ", ".join(map(str, row))
  comma = "," if i < len(rho_matrix) - 1 else ""
  lines.append(f"    '{{{row_vals}}}{comma}")

lines.append("  };")
lines.append("")
lines.append("  // INV_DELAY[ro_index][inv_index] — propagation delay in ps")
lines.append("  // Outer dimension: RO index (0 to N_RO-1)")
lines.append("  // Inner dimension: inverter stage index (0 to N_INV-1)")
lines.append(f"  localparam int INV_DELAY [0:{N_RO-1}][0:{N_INV-1}] = '{{")

for i in range(N_RO):
    inv_vals = ", ".join(ps_to_timescale(delays[i][j]) for j in range(N_INV))
    comma = "," if i < N_RO - 1 else ""
    lines.append(f"    /* RO[{i:02d}] */ '{{{inv_vals}}}{comma}")

lines.append("  };")
lines.append("")

# also emiting per-RO base means as a convenience (useful for debug / entropy analysis)
lines.append("  // RO_MEAN[ro_index] — the base mean delay assigned to each RO (ps)")
lines.append("  // Reflects inter-oscillator process variation")
mean_vals = ", ".join(ps_to_timescale(ro_means[i]) for i in range(N_RO))
lines.append(f"  localparam int RO_MEAN [0:{N_RO-1}] = '{{{mean_vals}}};")
lines.append("")
lines.append("endpackage : ro_delay_pkg")
lines.append("")

sv_text = "\n".join(lines)

# write output 
with open(OUTPUT_FILE, "w") as f:
    f.write(sv_text)

print(f"Generated '{OUTPUT_FILE}'")
print(f"  ROs               : {N_RO}")
print(f"  Inverters         : {N_INV}")
print(f"  RCT Threshold     : {RCT_THRESHOLD}")
print(f"  APT BIT WINDOW    : {APT_BIT_WINDOW}")
print(f"  APT Threshold     : {APT_THRESHOLD}")
print(f"  Consecutive errors: {CONSECUTIVE_ERRORS}")
print(f"  Delay range       : {delays.min():.1f} ps - {delays.max():.1f} ps")
print(f"  Mean per RO (ps)  : {ro_means.round(1)}")
