import math
from pathlib import Path
from scipy.stats import binom

SCRIPT_DIR = Path(__file__).parent.resolve()

# configuration
CONSECUTIVE_ERRORS = 3  # number consecutive errors in health tests
DRBG_CYCLES = 1024      # number of cycles the Keccak block uses feedback

# health tests parameters as per IST standard
ALPHA = 0.01           # false positive probability (NIST standard)
H_MIN = 0.9982         # measured min-entropy per bit (your design's measured value)
APT_BIT_WINDOW = 1024  # APT window size (fixed by NIST SP 800-90B for binary sources)
# p = most likely symbol probability, derived from min-entropy
# as per NIST SP 800-90B standard, p = 2^(-H_min)
# This is the probability of the MOST LIKELY symbol.
# For a nearly balanced source (H_min close to 1), p is close to 0.5.
p = 2 ** (-H_MIN)

# 1. RCT threshold calculation
"""
C = 1 + ⌈-log₂(alpha) / Hₘᵢₙ⌉

Where:
  C     = RCT threshold
  alpha = False positive probability (0.01 as per NIST standard)
  Hₘᵢₙ  = Minimum entropy per bit (0.9982 for the design config)
  ⌈...⌉ = Ceiling function (round UP)
"""
RCT_THRESHOLD = 1 + math.ceil(-math.log2(ALPHA) / H_MIN)

# 2. APT threshold calculation
"""
C = 1 + iCDF_Binomial(W, p, 1 - alpha)

where iCDF_Binomial(n, p, q) is the smallest integer C such that:
  P(X <= C) >= q     i.e. the quantile function

Equivalently, find smallest C such that:
  P(X >= C) <= alpha
where X ~ Binomial(W, p)

The +1 shift is explicit in the NIST spec to ensure the inequality
P(X >= C) <= alpha is strictly satisfied
"""
apt_icdf = binom.ppf(1 - ALPHA, APT_BIT_WINDOW, p)
APT_THRESHOLD = int(apt_icdf) + 1

# Keccak round constants
def keccak_round_constants():
  lfsr = 0x01
  RC = [0]*24

  for i in range(24):
    rc = 0
    for j in range(7):
      if lfsr & 0x01:
        rc ^= 1 << ((1 << j) - 1)

      # advance LFSR (polynomial x^8 + x^6 + x^5 + x^4 + 1)
      if lfsr & 0x80:
        lfsr = ((lfsr << 1) & 0xFF) ^ 0x71
      else:
        lfsr = (lfsr << 1) & 0xFF

    RC[i] = rc

  return RC

KECCAK_RC = keccak_round_constants()

OUTPUT_FILE = SCRIPT_DIR / ".." / "rtl" / "ro_param_pkg.sv"

# 5x5 Rho Offsets Matrix
rho_matrix = [
  [0, 36, 3, 41, 18],
  [1, 44, 10, 45, 2],
  [62, 6, 43, 15, 61],
  [28, 55, 25, 21, 56],
  [27, 20, 39, 8, 14]
]

# build package string 
lines = []
lines.append("// AUTO-GENERATED by gen_param.py")
lines.append("//")
lines.append(f"// Model parameters:")
lines.append(f"//   RCT Threshold  = {RCT_THRESHOLD}")
lines.append(f"//   APT Bit Window = {APT_BIT_WINDOW}")
lines.append(f"//   APT Threshold  = {APT_THRESHOLD}")
lines.append(f"//   CONSECUTIVE_ERRORS = {CONSECUTIVE_ERRORS}")
lines.append(f"//   DRBG CYCLES = {DRBG_CYCLES}")
lines.append("")
lines.append("`timescale 1ps/1ps")
lines.append("")
lines.append("package ro_param_pkg;")
lines.append("")
lines.append(f"  // NIST SP 800-90B Repetition Count Test (RCT) Threshold")
lines.append(f"  localparam int RCT_THRESHOLD = {RCT_THRESHOLD};")
lines.append(f"  // NIST SP 800-90B Adaptive Proportion Test (APT) bit window")
lines.append(f"  localparam int APT_BIT_WINDOW = {APT_BIT_WINDOW};")
lines.append(f"  // NIST SP 800-90B Adaptive Proportion Test (APT) Threshold")
lines.append(f"  localparam int APT_THRESHOLD = {APT_THRESHOLD};")
lines.append(f"  // number consecutive errors in health tests")
lines.append(f"  localparam int CONSECUTIVE_ERRORS = {CONSECUTIVE_ERRORS};")
lines.append(f"  // number of cycles the Keccak block uses feedback")
lines.append(f"  localparam int DRBG_CYCLES = {DRBG_CYCLES};")
lines.append("")
lines.append("  // RHO_OFFSETS[row][col] - Fixed rotation constants for Keccak/SHA3")
lines.append("  localparam int RHO_OFFSETS [0:4][0:4] = '{")

for i, row in enumerate(rho_matrix):
  row_vals = ", ".join(map(str, row))
  comma = "," if i < len(rho_matrix) - 1 else ""
  lines.append(f"    '{{{row_vals}}}{comma}")

lines.append("  };")
lines.append("")
lines.append("  // Keccak-f[1600] Round Constants")
lines.append("  localparam logic [63:0] KECCAK_RC [0:23] = '{")

for i, rc in enumerate(KECCAK_RC):
  comma = "," if i < 23 else ""
  lines.append(f"    64'h{rc:016X}{comma}")

lines.append("  };")
lines.append("")
lines.append("endpackage : ro_param_pkg")
lines.append("")

sv_text = "\n".join(lines)

# write output 
with open(OUTPUT_FILE, "w") as f:
  f.write(sv_text)

print(f"Generated '{OUTPUT_FILE}'")
print(f"  RCT Threshold     : {RCT_THRESHOLD}")
print(f"  APT BIT WINDOW    : {APT_BIT_WINDOW}")
print(f"  APT Threshold     : {APT_THRESHOLD}")
print(f"  Consecutive errors: {CONSECUTIVE_ERRORS}")
print(f"  DRBG CYCLES       : {DRBG_CYCLES}")
