import subprocess
import os
import sys
import re
import tempfile


def get_block_dependencies(block: str) -> list[str]:
    """
    Submodule .sv files instantiated by `block` that Yosys needs on top of
    whatever `block`.sv itself imports. Mirrors get_block_dependencies() in
    block_lvl_lint.tcl / block_lvl_synth.tcl -- keep these three in sync.
    """
    deps = {
        "cipher": ["sbox.sv", "shiftRows.sv", "mixColumns.sv", "addRoundKey.sv", "icg.sv"],
        "addRoundKey": ["icg.sv"],
        "sbox": ["icg.sv"],
        "trng_sbox_top": ["trng.sv", "sbox.sv", "icg.sv"],
        # The unmasked S-Box is a package inside unmasked_cipher.sv itself
        # (unmkased_sbox), so no composite_field_math.sv here -- that is the
        # masked S-Box's dependency, and this datapath does not use it.
        "unmasked_cipher": ["shiftRows.sv", "mixColumns.sv", "icg.sv"],
        # trng_param_pkg.sv must be read before drbg_utilities.sv: the
        # health_tests and entropy_clctr modules in it read RCT_THRESHOLD,
        # APT_BIT_WINDOW and APT_THRESHOLD from that package. It cannot be
        # auto-discovered, because cbc_mac.sv does not import it itself --
        # drbg_utilities.sv does, and discover_sources only parses the top
        # block's imports. trng_param_pkg.sv is generated by gen_param.py; the
        # Makefile's $(BLOCK_DEPS) guarantees it exists before lint or synth runs.
        "cbc_mac": [
            "trng_param_pkg.sv", "drbg_utilities.sv",
            "unmasked_cipher.sv", "shiftRows.sv", "mixColumns.sv", "icg.sv",
        ],
        # ctr_drbg instantiates only icg and unmasked_cipher -- no health tests
        # and no entropy collector -- so drbg_utilities.sv and trng_param_pkg.sv
        # are deliberately absent. addRoundKey_AES256 lives inside
        # unmasked_cipher.sv, so it needs no file of its own.
        "ctr_drbg": ["unmasked_cipher.sv", "shiftRows.sv", "mixColumns.sv", "icg.sv"],
        # iv_gen is the full entropy pipeline: cbc_mac (conditioner + health
        # tests + collector) and ctr_drbg, each with its own unmasked_cipher
        # instance. It needs the union of both blocks' dependencies plus the two
        # blocks themselves. trng_param_pkg.sv stays first for the same reason
        # as in cbc_mac -- drbg_utilities.sv reads from it.
        "iv_gen": [
            "trng_param_pkg.sv", "drbg_utilities.sv",
            "unmasked_cipher.sv", "shiftRows.sv", "mixColumns.sv",
            "cbc_mac.sv", "ctr_drbg.sv", "icg.sv",
        ],
    }
    return deps.get(block, [])


def discover_sources(rtl_dir: str, block: str) -> list[str]:
    """
    Return an ordered list of .sv files needed for `block`.
    Parses 'import <pkg>::' lines from the block file and
    prepends any matching *pkg*.sv found in rtl_dir, then adds
    this block's known submodule dependencies.
    """
    main_file = os.path.join(rtl_dir, f"{block}.sv")
    if not os.path.exists(main_file):
        print(f"Error: RTL file not found: {main_file}")
        sys.exit(1)

    with open(main_file, "r") as fh:
        content = fh.read()

    sources = []

    # Match every "import <identifier>::" in the file
    for pkg_name in re.findall(r'\bimport\s+([A-Za-z_]\w*)\s*::', content):
        pkg_file = os.path.join(rtl_dir, f"{pkg_name}.sv")
        if os.path.exists(pkg_file) and pkg_file not in sources:
            print(f"  [auto] including package: {pkg_file}")
            sources.append(pkg_file)

    # Submodule dependencies (instantiated modules, not packages)
    for dep in get_block_dependencies(block):
        dep_file = os.path.join(rtl_dir, dep)
        if os.path.exists(dep_file) and dep_file not in sources:
            print(f"  [auto] including module:  {dep_file}")
            sources.append(dep_file)

    print(f"  [auto] including block:   {main_file}")
    sources.append(main_file)
    return sources


def build_yosys_script(template: str, block: str, sources: list[str]) -> str:
    """
    Replace template variables and inject the discovered sources as one
    read_slang argument list.
    """
    read_sources = " ".join(sources)
    script = template.replace("${READ_SOURCES}", read_sources)
    script = script.replace("${BLOCK}", block)
    script = script.replace(
        "${LIBERTY}",
        os.environ.get(
            "LIBERTY", "/opt/pdks/nangate45/lib/NangateOpenCellLibrary_typical.lib"
        ),
    )
    script = script.replace(
        "${REPORT_DIR}",
        os.environ.get("REPORT_DIR", os.path.join(os.path.dirname(__file__), "reports")),
    )
    if os.environ.get("SCHEMATIC", "0") not in ("", "0", "false", "False"):
        schematic_command = (
            f"show -format dot -prefix {os.environ.get('REPORT_DIR', os.path.join(os.path.dirname(__file__), 'reports'))}/{block}_schematic {block}"
        )
    else:
        schematic_command = "# schematic disabled"
    script = script.replace("${SCHEMATIC_COMMAND}", schematic_command)
    return script


def dot_to_pdf(dot_file: str, pdf_file: str) -> None:
    if os.path.exists(dot_file):
        print(f"--- Converting schematic → PDF: {pdf_file} ---")
        subprocess.run(["dot", "-Tpdf", dot_file, "-o", pdf_file], check=True)
    else:
        print("Warning: .dot file not found — skipping PDF conversion.")


def run_yosys() -> None:
    block = os.environ.get("BLOCK", "").strip()
    if not block:
        print("Error: BLOCK environment variable not set.")
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    report_dir = os.environ.get("REPORT_DIR", os.path.join(script_dir, "reports"))
    os.makedirs(report_dir, exist_ok=True)
    rtl_dir = os.path.normpath(os.path.join(script_dir, "../rtl"))

    # Discover only the files this block needs
    sources = discover_sources(rtl_dir, block)

    # Load the .ys template
    template_path = os.path.join(script_dir, "block_lvl_synth.ys")
    with open(template_path, "r") as fh:
        template = fh.read()

    script_content = build_yosys_script(template, block, sources)

    tmp_path = None
    try:
        fd, tmp_path = tempfile.mkstemp(suffix=".ys", dir=report_dir)
        with os.fdopen(fd, "w") as tmp:
            tmp.write(script_content)

        print(f"--- Launching Yosys for: {block} ---")
        result = subprocess.run(["yosys", "-s", tmp_path], cwd=script_dir)
        if result.returncode != 0:
            print(f"Error: Yosys exited with code {result.returncode}.")
            sys.exit(result.returncode)

        # Convert schematic only when explicitly requested.
        if os.environ.get("SCHEMATIC", "0") not in ("", "0", "false", "False"):
            dot_to_pdf(
                os.path.join(report_dir, f"{block}_schematic.dot"),
                os.path.join(report_dir, f"{block}_schematic.pdf"),
            )

    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)


if __name__ == "__main__":
    run_yosys()
