# OpenSTA analysis for a mapped Nangate45 netlist generated by Yosys.
# The Makefile supplies LIBERTY, TOP, NETLIST, OUT_DIR and FREQ_MHZ.

set liberty  $::env(LIBERTY)
set top      $::env(TOP)
set netlist  $::env(NETLIST)
set out_dir  $::env(OUT_DIR)
set freq_mhz $::env(FREQ_MHZ)

if {$freq_mhz <= 0} {
    puts stderr "FREQ_MHZ must be greater than zero"
    exit 1
}

file mkdir $out_dir
set clk_period [expr {1000.0 / $freq_mhz}]

read_liberty $liberty
read_verilog $netlist
link_design $top

# Most sequential AES blocks expose clk. Pure combinational blocks such as
# ShiftRows and MixColumns do not, so analyze those as unconstrained paths.
set clk_ports [get_ports clk]
if {[llength $clk_ports] > 0} {
    create_clock -name clk -period $clk_period $clk_ports

    set data_inputs {}
    foreach port [all_inputs] {
        if {[get_full_name $port] ne "clk"} {
            lappend data_inputs $port
        }
    }
    if {[llength $data_inputs] > 0} {
        set_input_delay 0.0 -clock clk $data_inputs
    }
    if {[llength [all_outputs]] > 0} {
        set_output_delay 0.0 -clock clk [all_outputs]
    }

    report_checks -path_delay min_max -format full_clock_expanded \
        > [file join $out_dir timing.rpt]
} else {
    report_checks -unconstrained -path_delay max -format full \
        > [file join $out_dir timing.rpt]
}

report_wns >> [file join $out_dir timing.rpt]
report_tns >> [file join $out_dir timing.rpt]
report_power > [file join $out_dir power.rpt]

puts "------------------------------------------------------------"
puts "OpenSTA summary for $top"
puts "Target frequency: ${freq_mhz} MHz"
puts "Timing report: [file join $out_dir timing.rpt]"
puts "Power report:  [file join $out_dir power.rpt]"
report_wns
report_tns
puts "------------------------------------------------------------"
