"""
Cocotb testbench for the AES top block (`aes.sv`), driven through `aes_top.sv`.

    make run_test_suite block=aes_top
    make run_test       block=aes_top test=ecb_sp80038a_encrypt

STRUCTURE
---------
This file holds test bodies only. The layers underneath it are separate modules
so they can be reasoned about (and reused) on their own:

    aes_ref_model.py   golden reference for all five modes, self-checked
                       against NIST SP 800-38A Appendix F at import time
    aes_testbench.py   bus driver, output monitor, continuous protocol checker,
                       dual-domain noise sources, bring-up
    aes_top.sv         flat-port wrapper generated by rtl/gen_top.py -- aes.sv's
                       only port is a SystemVerilog interface, which Verilator
                       cannot elaborate as a simulation top

The block-level TBs in this directory are single ~1000-line files that each
re-implement the AES S-box, the key schedule and a `NoiseBitBuffer`. Nothing is
duplicated here: the block cipher is imported from cipher_tb/invCipher_tb via
aes_ref_model, and there is exactly one `wait_signal` signature.

WHAT IS BEING TESTED
--------------------
`aes.sv` is a mode wrapper. The AES round datapath itself is already covered by
cipher_tb / invCipher_tb / sbox_tb, so the value at this level is in everything
those cannot see:

  * the five mode algorithms end to end against published vectors,
  * the chaining state that carries from block to block within a message, and
    that must NOT carry from one message to the next,
  * the VALID/READY contract in both directions, including backpressure and
    idle senders,
  * the IV/counter context ports -- what the DUT reports, what it accepts, and
    whether a counter can ever repeat,
  * reset, enable-gating and invalid configuration,
  * whether a signal the interface says may be dropped after `inREADY` is in
    fact still needed later.

TEST NAMING
-----------
Descriptive names with a `# ==== TCn ====` banner, matching the newest block TBs
(trng_tb, cbc_mac_tb, iv_gen_tb) and keeping `test=<name>` readable.

A NOTE ON EXPECTED FAILURES
---------------------------
Nothing here is written to pass. Each test asserts what the design documents or
what the relevant standard requires, and the assertion message says which. A
failure is a statement about the RTL, not a knob to turn.
"""

import random

import cocotb
from cocotb.triggers import ClockCycles, FallingEdge, RisingEdge

import aes_ref_model as M
from aes_ref_model import (
    AesModeModel, SP800_38A_CBC, SP800_38A_CFB128, SP800_38A_ECB, SP800_38A_OFB,
    nist_bytes_to_rtl_state, rtl_hex, rtl_state_to_nist_bytes,
)
from cipher_tb import _add_round_key
from aes_testbench import (
    BLOCK_TIMEOUT, CONFIG_SETTLE, EDGE_BLOCKS, EDGE_KEYS_128, INVALID_CFB_SEGS,
    INVALID_MODES, IV_TIMEOUT, ST_ARM, ST_NAMES, AesConfig, HoldStyle,
    apply_config, bringup, compare, dut_state, expected_outputs, is_x,
    park_inputs, probe, rand_blocks, recv_block, reset_dut, run_message,
    send_block, wait_signal,
)

# Runtime backstop. Every wait in aes_testbench is already a bounded cycle loop,
# but a deadlock inside a `while True` driver would otherwise hang the run
# forever -- no existing TB in this repo has this guard.
TIMEOUT_MS = 400
SOAK_TIMEOUT_MS = 2000

# NIST SP 800-38A Appendix F message and context, shared by every mode there.
PT_38A = [nist_bytes_to_rtl_state(list(bytes.fromhex(h))) for h in (
    "6bc1bee22e409f96e93d7e117393172a", "ae2d8a571e03ac9c9eb76fac45af8e51",
    "30c81c46a35ce411e5fbc1191a0a52ef", "f69f2445df4f9b17ad2b417be66c3710")]
IV_38A = nist_bytes_to_rtl_state(list(bytes.fromhex("000102030405060708090a0b0c0d0e0f")))
CTR0_38A = nist_bytes_to_rtl_state(list(bytes.fromhex("f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff")))

KEY_128 = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
KEY_192 = bytes.fromhex("8e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b")
KEY_256 = bytes.fromhex("603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4")
KEYS = {128: KEY_128, 192: KEY_192, 256: KEY_256}


def rtl_blocks(hex_list):
    return [nist_bytes_to_rtl_state(list(bytes.fromhex(h))) for h in hex_list]


def banner(dut, text):
    dut._log.info("=" * 70)
    dut._log.info(text)
    dut._log.info("=" * 70)


async def run_and_check(dut, cfg, blocks, *, context=None, partial_bits=None,
                        ready_delay=0, send_gap=0, label="", ctr_increment="nist"):
    """Push a message through the DUT and scoreboard it.

    For the paths that generate their own IV/counter (CBC/CFB/OFB encryption,
    CTR encryption) the chaining context is whatever the DUT reports on
    `encCntxtOut`; the reference is then computed from that value, so the test
    checks the mode algorithm rather than re-deriving an IV it cannot know.
    Whether that reported context is itself sane -- fresh, unique, actually the
    one used -- is a separate question, asked by the IV tests.
    """
    apply_config(dut, cfg)
    res = await run_message(dut, cfg, blocks, enc_cntxt_in=(context or 0),
                            partial_bits=partial_bits, ready_delay=ready_delay,
                            send_gap=send_gap)
    used = res.enc_cntxt_out if cfg.needs_generated_iv or (
        cfg.mode == "CTR" and not cfg.decrypt) else (context or 0)
    want = expected_outputs(cfg, blocks, used, partial_bits=partial_bits,
                            ctr_increment=ctr_increment)
    compare(dut, cfg, res.outputs, want, context=used, label=label or str(cfg))
    return res, used


# ===========================================================================
# TC0 -- Testbench integrity
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def model_self_check(dut):
    """The golden model reproduces every NIST SP 800-38A Appendix F vector.

    Runs the reference implementation against the published ECB/CBC/CFB128/OFB/CTR
    vectors for all three key sizes before any DUT signal is driven, so a
    modelling mistake can never be reported as an RTL bug. The mode vectors did
    not exist anywhere in this repo before; the block TBs only carried raw
    FIPS 197 CIPHER vectors.
    """
    banner(dut, "TC0: golden model vs NIST SP 800-38A Appendix F")
    M.self_check()
    dut._log.info("  ECB/CBC/CFB128/OFB/CTR x 128/192/256 all reproduce")
    dut._log.info(f"  CFB note : {M.CFB_SEGMENT_ORDER_NOTE}")
    dut._log.info(f"  CTR note : {M.CTR_INCREMENT_NOTE}")


# ===========================================================================
# TC1..TC6 -- Reset, enable gating, power
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def reset_output_state(dut):
    """After reset every output is zero and the FSM is parked in ARM.

    aes.sv:296-311 lists the reset values; this asserts each of them on the real
    outputs rather than trusting the branch exists.
    """
    banner(dut, "TC1: reset clears all outputs and parks the FSM in ARM")
    env = await bringup(dut)
    await ClockCycles(dut.clk, 4)

    for name in ("output_block", "encCntxtOut", "inREADY", "outVALID"):
        assert int(getattr(dut, name).value) == 0, (
            f"{name} = 0x{int(getattr(dut, name).value):x} after reset, expected 0")

    fsm = probe(dut, "AES.fsm_state")
    if fsm is not None:
        assert int(fsm.value) == ST_ARM, (
            f"fsm_state = {ST_NAMES.get(int(fsm.value))} after reset, expected ARM")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def reset_x_freedom(dut):
    """No DUT output carries X/Z once reset is released.

    `--x-assign 0` makes an uninitialised signal read as 0, so a plain
    "must be zero" check passes for the wrong reason. This looks at
    resolvability directly -- something no existing TB in this repo does.
    """
    banner(dut, "TC2: outputs are X/Z-free after reset")
    env = await bringup(dut)
    await ClockCycles(dut.clk, 4)
    unresolved = [n for n in ("output_block", "encCntxtOut", "inREADY", "outVALID")
                  if is_x(getattr(dut, n))]
    assert not unresolved, (
        f"outputs still unresolved (X/Z) after reset: {unresolved}. Under "
        f"--x-assign 0 these would read as 0 and silently pass a zero check")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def reset_mid_operation_recovery(dut):
    """A reset asserted mid-encryption is absorbed, and the next message is correct.

    Reset is the only documented recovery path out of a stalled transaction, so
    it has to work from an arbitrary point inside SHOOT -- not just from idle.
    """
    banner(dut, "TC3: reset in the middle of SHOOT, then a clean message")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)

    # Start a block and pull the plug partway through the round sequence.
    await send_block(dut, PT_38A[0], first=True)
    await ClockCycles(dut.clk, 60)
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 8)
    dut.rst_n.value = 1
    park_inputs(dut)
    dut.enb_n.value = 0
    await RisingEdge(dut.clk)

    assert int(dut.outVALID.value) == 0, "outVALID survived a reset"
    assert int(dut.output_block.value) == 0, "output_block survived a reset"

    await run_and_check(dut, cfg, PT_38A[:2], label="TC3 post-reset ECB")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def enable_gating_freezes_fsm(dut):
    """With enb_n high the DUT makes no progress at all, and resumes where it left off.

    aes.sv's ICG enable is `~enb_n | ~rst_n` (aes.sv:186-189), so raising enb_n
    stops the block's clock outright. Every mode-FSM register must therefore be
    bit-identical across the parked window.
    """
    banner(dut, "TC4: enb_n freezes the whole mode FSM")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    await send_block(dut, PT_38A[0], first=True)
    await ClockCycles(dut.clk, 40)

    names = ["AES.fsm_state", "AES.cipherIn", "AES.cipher_enb_n", "AES.seg_cntr",
             "AES.temp", "AES._temp", "AES.ctr_mode_cntr"]
    probes = {n: probe(dut, n) for n in names}
    probes = {n: h for n, h in probes.items() if h is not None}

    dut.enb_n.value = 1
    await ClockCycles(dut.clk, 2)             # let the gate close
    frozen = {n: int(h.value) for n, h in probes.items()}
    for cyc in range(200):
        await FallingEdge(dut.clk)
        for n, want in frozen.items():
            got = int(probes[n].value)
            assert got == want, (
                f"{n} changed while enb_n was high (cycle {cyc}): "
                f"0x{got:x} != 0x{want:x} -- the ICG is not actually gating the "
                f"mode FSM's clock")

    dut.enb_n.value = 0
    out = await recv_block(dut)
    want = cfg.model().encrypt_block(PT_38A[0])
    assert out.data == want, (
        f"block corrupted by the enb_n pause: got {rtl_hex(out.data)}, "
        f"want {rtl_hex(want)}")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def disable_while_outvalid(dut):
    """enb_n freezes the AES; a pending output is HELD, never withdrawn.

    POLICY (settled 2026-09-08): a disable is a *freeze*, not a soft reset.

    aes.sv's ICG enable is `~enb_n | ~rst_n` (aes.sv:186-189), so raising enb_n
    removes every clock edge from the block and each register -- `inREADY` and
    `outVALID` included -- holds its value. A manager that asked for a block and
    then disabled the AES gets that block back intact on re-enable; nothing is
    discarded. That is what preserves data integrity, and it is also what keeps
    output-channel rule C1 (VALID may not drop without READY) true across a
    disable, which no "clear the handshake on enb_n" policy can do.

    The corollary is an integration requirement the AES cannot enforce for
    itself: a frozen AES cannot observe a handshake, so the manager must not
    drive `outREADY` (or `inVALID`) at a disabled AES. Phase 3 pins that down --
    the DUT correctly ignores it, which is exactly why the manager must not rely
    on it being seen.
    """
    banner(dut, "TC5: enb_n while an output is pending -- freeze, not withdraw")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    want = cfg.model().encrypt_block(PT_38A[0])

    await send_block(dut, PT_38A[0], first=True)
    await wait_signal(dut, dut.outVALID, 1, BLOCK_TIMEOUT, "outVALID")

    held = {"output_block": int(dut.output_block.value),
            "encCntxtOut": int(dut.encCntxtOut.value),
            "inREADY":     int(dut.inREADY.value),
            "outVALID":    int(dut.outVALID.value)}
    fsm = probe(dut, "AES.fsm_state")
    held_fsm = int(fsm.value) if fsm is not None else None

    # -- phase 1: the freeze holds the entire output channel, not just the data --
    dut.enb_n.value = 1
    await ClockCycles(dut.clk, 10)
    for name, exp in held.items():
        got = int(getattr(dut, name).value)
        assert got == exp, (
            f"{name} changed while enb_n was high (0x{exp:x} -> 0x{got:x}). A "
            f"disabled AES must freeze, not withdraw: the manager asked for this "
            f"block and is entitled to find it unchanged on re-enable")
    if held_fsm is not None:
        assert int(fsm.value) == held_fsm, "fsm_state advanced while enb_n was high"

    # -- phase 2: a frozen AES cannot participate in a handshake ----------------
    dut.outREADY.value = 1
    await ClockCycles(dut.clk, 5)
    assert int(dut.outVALID.value) == 1, (
        "outVALID cleared while enb_n was high, so the DUT appears to have "
        "completed a transfer it has no clock to process -- that block would be "
        "lost. A frozen AES must ignore outREADY")
    if held_fsm is not None:
        assert int(fsm.value) == held_fsm, (
            "fsm_state advanced in response to outREADY while enb_n was high")
    dut.outREADY.value = 0
    await ClockCycles(dut.clk, 2)
    dut._log.info("  outREADY while disabled was ignored, as the freeze requires")

    # -- phase 3: re-enable, and the very same block is delivered intact --------
    dut.enb_n.value = 0
    out = await recv_block(dut)
    assert out.data == want, (
        f"the pending block did not survive the disable: got {rtl_hex(out.data)}, "
        f"want {rtl_hex(want)}")
    await ClockCycles(dut.clk, 2)
    assert int(dut.outVALID.value) == 0, (
        "outVALID did not clear after the post-resume transfer")
    dut._log.info("  block held across the disable and delivered intact on resume")

    # -- phase 4: the disable left no residue behind ----------------------------
    res = await run_message(dut, cfg, [PT_38A[1]])
    compare(dut, cfg, res.outputs, cfg.model().ecb_encrypt([PT_38A[1]]),
            label="TC5 message after the disable")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def reset_during_iv_generation(dut):
    """A reset while the IV pipeline is mid-seed leaves a recoverable DUT.

    CBC/CFB/OFB encryption blocks on `iv_valid` from iv_gen, which is a
    ~1200-cycle conditioner run followed by the DRBG. Resetting inside that
    window must not leave the AES waiting for an IV that will never arrive.
    """
    banner(dut, "TC6: reset during IV generation, then a clean CBC message")
    env = await bringup(dut)
    cfg = AesConfig("CBC", KEY_128)
    apply_config(dut, cfg)

    dut.input_block.value = PT_38A[0]
    dut.first.value = 1
    dut.inVALID.value = 1
    await ClockCycles(dut.clk, 300)           # partway through the seed
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 8)
    dut.rst_n.value = 1
    park_inputs(dut)
    dut.enb_n.value = 0
    await RisingEdge(dut.clk)

    await run_and_check(dut, cfg, PT_38A[:2], label="TC6 post-reset CBC")
    env.checker.check()


# ===========================================================================
# TC7..TC10 -- Configuration decode
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def invalid_mode_is_inert(dut):
    """mode[2:0] of 000/110/111 produces no handshake and no output.

    aes.sv:705-720's `default` branch parks everything. An undecoded mode must
    never look like a working one -- silently encrypting under an unintended
    mode is worse than refusing.
    """
    banner(dut, "TC7: undecoded mode values are inert")
    env = await bringup(dut)
    for bad in INVALID_MODES:
        await reset_dut(dut)
        dut.mode.value = bad
        dut.key_size.value = 0b01
        dut.master_key.value = AesModeModel(KEY_128).master_key_rtl
        dut.input_block.value = PT_38A[0]
        dut.first.value = 1
        dut.inVALID.value = 1
        dut.outREADY.value = 1
        await ClockCycles(dut.clk, 500)
        assert int(dut.inREADY.value) == 0, (
            f"mode=0b{bad:03b} asserted inREADY -- an undecoded mode accepted a "
            f"block it has no algorithm for")
        assert int(dut.outVALID.value) == 0, (
            f"mode=0b{bad:03b} asserted outVALID")
        assert int(dut.output_block.value) == 0, (
            f"mode=0b{bad:03b} produced output 0x{int(dut.output_block.value):032x}")
        dut._log.info(f"  mode=0b{bad:03b}: inert as expected")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def invalid_cfb_segment(dut):
    """An out-of-spec cfb_seg_bits must stay contained: no hang, no damage.

    SCOPE. `cfb_seg_bits` of 000/110/111 is out of spec (aes.sv:91-100 defines
    only 001..101). What the block *should* do about that is an open design
    decision, not something the RTL has ever promised:

        (a) don't care -- out-of-spec config is a software bug   <- today
        (b) refuse     -- stay parked, never handshake           <- what an
                          undecoded mode[2:0] already does
        (c) report     -- raise segINVALID                       <- planned in
                          docs/status_register.md

    An earlier version of this test asserted (b). That was the testbench
    encoding an opinion as a requirement, and it is not asserted here. What IS
    asserted is the property that holds under every one of the three policies
    and that a consumer genuinely depends on: a misconfigured request must not
    hang the block, and must not damage the traffic that follows it.

    The observed handshake behaviour is logged rather than checked, so the
    current policy is visible in the run without failing it.

    TODO: once the status register lands, tighten this to assert the chosen
    policy -- for (c), that segINVALID is raised for exactly these encodings.
    """
    banner(dut, "TC8: out-of-spec cfb_seg_bits stays contained")
    env = await bringup(dut)
    good = AesConfig("CFB", KEY_128, cfb_seg_bits=128)

    for bad in INVALID_CFB_SEGS:
        await reset_dut(dut)
        dut.mode.value = 0b0011               # CFB encrypt
        dut.key_size.value = 0b01
        dut.master_key.value = AesModeModel(KEY_128).master_key_rtl
        dut.cfb_seg_bits.value = bad
        dut.input_block.value = PT_38A[0]
        dut.first.value = 1
        dut.inVALID.value = 1
        dut.outREADY.value = 1

        # Long enough for the IV pipeline (~1100 clk) plus a full block, so a
        # "no output" result means the configuration really is inert rather than
        # merely slow.
        got_valid, got_data, got_ctx = 0, 0, 0
        for _ in range(CONFIG_SETTLE):
            await FallingEdge(dut.clk)
            if int(dut.outVALID.value):
                got_valid = 1
                got_data = int(dut.output_block.value)
                got_ctx = int(dut.encCntxtOut.value)
                break
        policy = ("(b) refused -- stayed parked" if not got_valid else
                  "(a) handshook out zeros" if got_data == 0 else
                  "handshook out NON-zero data")
        dut._log.info(f"  cfb_seg_bits=0b{bad:03b}: outVALID={got_valid} "
                      f"output=0x{got_data:032x}  -> policy {policy}")
        if got_valid and got_ctx:
            dut._log.info(f"    note: consumed a generated IV "
                          f"(encCntxtOut=0x{got_ctx:032x}) for a request it "
                          f"cannot service")

        # Release the bus, then -- deliberately WITHOUT a reset -- run a real
        # CFB128 message. This is the containment check: whatever the block did
        # with the bogus request, it must not have left chaining state, a stuck
        # seg_cntr or a half-open handshake behind.
        await RisingEdge(dut.clk)
        dut.inVALID.value = 0
        dut.outREADY.value = 0
        dut.first.value = 0
        dut.input_block.value = 0

        assert int(dut.outVALID.value) == 0 or got_valid, (
            f"cfb_seg_bits=0b{bad:03b}: outVALID is asserted but was never seen "
            f"to rise -- the handshake is stuck. {dut_state(dut)}")

        apply_config(dut, good)
        res = await run_message(dut, good, PT_38A[:2])
        want = good.model().cfb_encrypt(PT_38A[:2], res.enc_cntxt_out, 128)
        compare(dut, good, res.outputs, want, context=res.enc_cntxt_out,
                label=f"TC8 valid CFB128 message after cfb_seg_bits=0b{bad:03b}")
        dut._log.info(f"    a following valid CFB128 message is unaffected")
    env.checker.check()


def zero_round_result(pt, key):
    """plaintext XOR w[0..3] -- what an Nr=0 'encryption' would emit."""
    m = AesModeModel(key)
    s = _add_round_key(rtl_state_to_nist_bytes(pt), m._enc.round_key(0))
    return nist_bytes_to_rtl_state(s)


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def key_size_reset_value(dut):
    """key_size=00 is documented as a reset value, not a key length.

    aes.sv:50-53 lists 00 as "reset value". cipher.sv:48 derives Nr from it as
    `{key_size[1]|key_size[0], key_size[1], key_size[0], 0}` = 0, so a cipher
    started with key_size=00 has Nr=0. Whatever the design intends, it must not
    hand out a block produced by a zero-round AES.
    """
    banner(dut, "TC9: key_size=00 must not produce a zero-round ciphertext")
    env = await bringup(dut)
    dut.mode.value = 0b0001
    dut.key_size.value = 0b00
    dut.master_key.value = AesModeModel(KEY_128).master_key_rtl
    dut.input_block.value = PT_38A[0]
    dut.first.value = 1
    dut.inVALID.value = 1
    dut.outREADY.value = 1
    await ClockCycles(dut.clk, 3000)
    if int(dut.outVALID.value):
        got = int(dut.output_block.value)
        assert got != zero_round_result(PT_38A[0], KEY_128), (
            f"key_size=00 produced {rtl_hex(got)}, which is exactly "
            f"plaintext XOR round-key-0 -- a single AddRoundKey with no rounds. "
            f"That is not encryption; the reset key_size value must be rejected "
            f"rather than run")
    else:
        dut._log.info("  key_size=00: inert (no outVALID) -- acceptable")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def mode_switch_between_messages(dut):
    """Switching mode between messages does not leak chaining state.

    Each mode's branch zeroes the registers it does not use, so a CBC message
    followed by an ECB message must give exactly the ECB answer -- no residual
    XOR with a leftover ciphertext or IV.
    """
    banner(dut, "TC10: ECB after CBC after ECB, no state leakage")
    env = await bringup(dut)
    ecb = AesConfig("ECB", KEY_128)
    cbc = AesConfig("CBC", KEY_128)

    await run_and_check(dut, ecb, PT_38A[:2], label="TC10 ECB #1")
    await run_and_check(dut, cbc, PT_38A[:2], label="TC10 CBC")
    await run_and_check(dut, ecb, PT_38A[:2], label="TC10 ECB #2")
    env.checker.check()


# ===========================================================================
# TC11..TC17 -- ECB
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_fips197_kat(dut):
    """FIPS 197 Appendix C.1/C.2/C.3 single-block vectors, all three key sizes.

    The narrowest possible check: one block, straight after reset, no chaining.
    If this fails nothing else in the file is meaningful.
    """
    banner(dut, "TC11: FIPS 197 C.1/C.2/C.3 single-block ECB")
    env = await bringup(dut)
    vectors = [
        (bytes.fromhex("000102030405060708090a0b0c0d0e0f"),
         "00112233445566778899aabbccddeeff", "69c4e0d86a7b0430d8cdb78070b4c55a"),
        (bytes.fromhex("000102030405060708090a0b0c0d0e0f1011121314151617"),
         "00112233445566778899aabbccddeeff", "dda97ca4864cdfe06eaf70a0ec0d7191"),
        (bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
         "00112233445566778899aabbccddeeff", "8ea2b7ca516745bfeafc49904b496089"),
    ]
    for key, pt_hex, ct_hex in vectors:
        await reset_dut(dut)
        cfg = AesConfig("ECB", key)
        pt = rtl_blocks([pt_hex])
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, pt)
        got = rtl_hex(res.outputs[0])
        assert got == ct_hex, (
            f"AES-{len(key)*8} ECB KAT: got {got}, want {ct_hex}")
        dut._log.info(f"  AES-{len(key)*8}: {got}")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_sp80038a_encrypt(dut):
    """SP 800-38A F.1.1/F.1.3/F.1.5 -- four-block ECB encryption, all key sizes.

    The first multi-block test in the file, and therefore the first that depends
    on the DUT being able to run a second block after a first.
    """
    banner(dut, "TC12: SP 800-38A F.1 ECB encryption, 4 blocks x 3 key sizes")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_ECB.items():
        await reset_dut(dut)
        cfg = AesConfig("ECB", bytes.fromhex(key_hex))
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, PT_38A)
        compare(dut, cfg, res.outputs, rtl_blocks(ct_hex),
                label=f"TC12 ECB-{bits} encrypt")
        dut._log.info(f"  AES-{bits}: 4/4 blocks match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_sp80038a_decrypt(dut):
    """SP 800-38A F.1.2/F.1.4/F.1.6 -- four-block ECB decryption, all key sizes.

    Exercises the invCipher datapath and the invSbox's separate TRNG handshake,
    which the encryption tests never touch.
    """
    banner(dut, "TC13: SP 800-38A F.1 ECB decryption, 4 blocks x 3 key sizes")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_ECB.items():
        await reset_dut(dut)
        cfg = AesConfig("ECB", bytes.fromhex(key_hex), decrypt=True)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, rtl_blocks(ct_hex))
        compare(dut, cfg, res.outputs, PT_38A, label=f"TC13 ECB-{bits} decrypt")
        dut._log.info(f"  AES-{bits}: 4/4 blocks match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_roundtrip_random(dut):
    """Random blocks survive an encrypt/decrypt round trip under all key sizes.

    A round trip catches a symmetric fault (e.g. a byte-order slip applied
    identically to both directions) that a one-directional KAT would miss only
    if the KAT itself is wrong -- so this runs alongside, not instead of, TC12.
    """
    banner(dut, "TC14: ECB random round trip")
    env = await bringup(dut)
    rng = random.Random(0xA35C0DE)
    for bits, key in KEYS.items():
        blocks = rand_blocks(rng, 3)
        await reset_dut(dut)
        enc = AesConfig("ECB", key)
        apply_config(dut, enc)
        ct = (await run_message(dut, enc, blocks)).outputs

        await reset_dut(dut)
        dec = AesConfig("ECB", key, decrypt=True)
        apply_config(dut, dec)
        pt = (await run_message(dut, dec, ct)).outputs
        compare(dut, dec, pt, blocks, label=f"TC14 ECB-{bits} round trip")
        dut._log.info(f"  AES-{bits}: 3/3 blocks round-tripped")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_edge_patterns(dut):
    """Degenerate and adversarial block patterns through ECB.

    All-zero, all-one, alternating and single-bit blocks. A datapath that drops,
    duplicates or transposes a lane usually still looks right on random data and
    fails immediately on a single set bit.
    """
    banner(dut, "TC15: ECB edge-pattern blocks")
    env = await bringup(dut)
    for key in EDGE_KEYS_128:
        await reset_dut(dut)
        cfg = AesConfig("ECB", key)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, EDGE_BLOCKS)
        compare(dut, cfg, res.outputs, cfg.model().ecb_encrypt(EDGE_BLOCKS),
                label=f"TC15 ECB key={key.hex()}")
        dut._log.info(f"  key={key.hex()}: {len(EDGE_BLOCKS)} patterns match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_first_is_ignored(dut):
    """`first` has no effect in ECB, whatever the sender does with it.

    aes.sv:84 says the signal "is ignored in ECB mode". Driving it high on every
    block, and then on none, must give byte-identical ciphertext.
    """
    banner(dut, "TC16: `first` is genuinely ignored in ECB")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)

    await reset_dut(dut)
    apply_config(dut, cfg)
    all_first = (await run_message(dut, cfg, PT_38A, mark_first=True)).outputs
    # mark_first=True only flags block 0; drive it on every block by hand.
    await reset_dut(dut)
    apply_config(dut, cfg)
    every = []
    for blk in PT_38A:
        await send_block(dut, blk, first=True)
        every.append((await recv_block(dut)).data)

    await reset_dut(dut)
    apply_config(dut, cfg)
    none = (await run_message(dut, cfg, PT_38A, mark_first=False)).outputs

    want = cfg.model().ecb_encrypt(PT_38A)
    compare(dut, cfg, all_first, want, label="TC16 first on block 0")
    compare(dut, cfg, every, want, label="TC16 first on every block")
    compare(dut, cfg, none, want, label="TC16 first never asserted")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ecb_key_change_between_messages(dut):
    """A new master_key takes effect on the next message with no reset.

    The key schedule is recomputed inside addRoundKey per encryption, so
    changing `master_key` between messages must be enough. A stale schedule
    would silently keep encrypting under the previous key.
    """
    banner(dut, "TC17: master_key change between messages")
    env = await bringup(dut)
    for key in (KEY_128, bytes.fromhex("000102030405060708090a0b0c0d0e0f"),
                bytes([0xFF] * 16), KEY_128):
        cfg = AesConfig("ECB", key)
        await run_and_check(dut, cfg, PT_38A[:2],
                            label=f"TC17 ECB key={key.hex()[:8]}..")
        dut._log.info(f"  key={key.hex()}: matches")
    env.checker.check()


# ===========================================================================
# TC18..TC23 -- CBC
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_encrypt_uses_reported_iv(dut):
    """C(0) really is E(P(0) XOR encCntxtOut).

    In CBC encryption the DUT generates its own IV and reports it on
    `encCntxtOut`. That report is the only way a peer can ever decrypt the
    message, so it has to be the IV that was actually used -- not a stale
    register, not the next one.
    """
    banner(dut, "TC18: CBC encryption -- reported IV is the IV used")
    env = await bringup(dut)
    cfg = AesConfig("CBC", KEY_128)
    apply_config(dut, cfg)
    res = await run_message(dut, cfg, PT_38A[:1])
    iv = res.enc_cntxt_out
    want = cfg.model().encrypt_block(PT_38A[0] ^ iv)
    assert res.outputs[0] == want, (
        f"CBC C(0) = {rtl_hex(res.outputs[0])} but E(P(0) XOR encCntxtOut) = "
        f"{rtl_hex(want)} with encCntxtOut = {rtl_hex(iv)}. The IV handed to the "
        f"peer is not the IV the block was encrypted with, so nothing can "
        f"decrypt this message")
    assert iv != 0, "encCntxtOut is zero -- no IV was generated"
    dut._log.info(f"  IV = {rtl_hex(iv)}, C0 confirmed")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_encrypt_multiblock(dut):
    """Four-block CBC encryption chains C(j) = E(P(j) XOR C(j-1)).

    Scoreboarded against the model seeded with the DUT's own reported IV, so
    this isolates the chaining recurrence from the IV source.
    """
    banner(dut, "TC19: CBC multi-block chaining, all key sizes")
    env = await bringup(dut)
    for bits, key in KEYS.items():
        await reset_dut(dut)
        cfg = AesConfig("CBC", key)
        _, iv = await run_and_check(dut, cfg, PT_38A, label=f"TC19 CBC-{bits} enc")
        dut._log.info(f"  AES-{bits}: 4/4 chained correctly (IV {rtl_hex(iv)})")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_decrypt_sp80038a(dut):
    """SP 800-38A F.2.2/F.2.4/F.2.6 -- CBC decryption with an externally supplied IV.

    The IV arrives on `encCntxtIn`. This is the path a real peer uses to decrypt
    something this chip previously encrypted, so a failure here means encrypted
    data is unrecoverable.
    """
    banner(dut, "TC20: SP 800-38A F.2 CBC decryption")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_CBC.items():
        await reset_dut(dut)
        cfg = AesConfig("CBC", bytes.fromhex(key_hex), decrypt=True)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, rtl_blocks(ct_hex), enc_cntxt_in=IV_38A)
        compare(dut, cfg, res.outputs, PT_38A, context=IV_38A,
                label=f"TC20 CBC-{bits} decrypt")
        dut._log.info(f"  AES-{bits}: 4/4 blocks match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_decrypt_first_block_context(dut):
    """The first CBC-decrypt block XORs with the IV, under the documented hold rule.

    aes.sv:460-461 chooses between the captured IV (`_temp`) and the previous
    ciphertext (`temp`) by reading `aesBus.first` *in the SHOOT state* -- long
    after the input handshake. aes.sv:81-88 mandates the Case-1 discipline, in
    which a compliant sender has already dropped `first` by then. So this test
    drives `first` exactly as the interface says it may be driven, and checks
    only the first output block: if the selection is wrong, block 0 comes back
    XORed with whatever `temp` happened to hold.
    """
    banner(dut, "TC21: CBC decrypt block 0 with Case-1 `first` timing")
    env = await bringup(dut)
    key = KEY_128
    ct = rtl_blocks(SP800_38A_CBC[128][1])
    cfg = AesConfig("CBC", key, decrypt=True, hold=HoldStyle.CASE1)
    apply_config(dut, cfg)
    res = await run_message(dut, cfg, ct[:1], enc_cntxt_in=IV_38A)
    want = cfg.model().cbc_decrypt(ct[:1], IV_38A)[0]
    assert res.outputs[0] == want, (
        f"CBC decrypt block 0 = {rtl_hex(res.outputs[0])}, want {rtl_hex(want)}.\n"
        f"  aes.sv:460 selects the IV with a live read of `first` while in SHOOT, "
        f"but aes.sv:81-88 lets the sender drop `first` as soon as inREADY is "
        f"seen -- which is what this test does. Under that contract the branch "
        f"picks `temp` (the previous ciphertext register) instead of `_temp` "
        f"(the captured IV). `first` must be latched at the input handshake and "
        f"the latched copy used in SHOOT")

    # Same message with the signal held far longer than the contract requires:
    # if this passes where the above failed, the hold discipline is the cause.
    await reset_dut(dut)
    cfg2 = AesConfig("CBC", key, decrypt=True, hold=HoldStyle.THROUGH_OUTPUT)
    apply_config(dut, cfg2)
    res2 = await run_message(dut, cfg2, ct[:1], enc_cntxt_in=IV_38A)
    dut._log.info(f"  Case-2 hold result: {rtl_hex(res2.outputs[0])} "
                  f"(want {rtl_hex(want)})")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_roundtrip(dut):
    """CBC encrypt then decrypt with the reported IV recovers the plaintext.

    This is the end-to-end property the `encCntxtOut` -> `encCntxtIn` contract
    exists to provide, exercised exactly the way an integrator would use it.
    """
    banner(dut, "TC22: CBC round trip through encCntxtOut -> encCntxtIn")
    env = await bringup(dut)
    rng = random.Random(0xCBC17)
    blocks = rand_blocks(rng, 3)
    for bits, key in KEYS.items():
        await reset_dut(dut)
        enc = AesConfig("CBC", key)
        apply_config(dut, enc)
        res = await run_message(dut, enc, blocks)
        iv = res.enc_cntxt_out

        await reset_dut(dut)
        dec = AesConfig("CBC", key, decrypt=True)
        apply_config(dut, dec)
        back = await run_message(dut, dec, res.outputs, enc_cntxt_in=iv)
        compare(dut, dec, back.outputs, blocks, context=iv,
                label=f"TC22 CBC-{bits} round trip")
        dut._log.info(f"  AES-{bits}: round trip OK (IV {rtl_hex(iv)})")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cbc_iv_uniqueness(dut):
    """Every CBC message gets a fresh IV; none repeats and none is zero.

    A repeated CBC IV under one key leaks whether two messages share a prefix.
    iv_gen exists to make that impossible, so the top level must actually
    consume a new IV per message rather than latching the first one.
    """
    banner(dut, "TC23: CBC IV freshness across messages")
    env = await bringup(dut)
    cfg = AesConfig("CBC", KEY_128)
    apply_config(dut, cfg)
    ivs = []
    for i in range(6):
        res = await run_message(dut, cfg, PT_38A[:1])
        ivs.append(res.enc_cntxt_out)
        dut._log.info(f"  message {i}: IV = {rtl_hex(res.enc_cntxt_out)}")
    assert 0 not in ivs, "a CBC message was encrypted under an all-zero IV"
    assert len(set(ivs)) == len(ivs), (
        f"CBC IV repeated across messages: {[rtl_hex(v) for v in ivs]}. Two "
        f"messages under one key sharing an IV leak their common prefix")
    env.checker.check()


# ===========================================================================
# TC24..TC29 -- CFB
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb128_encrypt_sp80038a(dut):
    """SP 800-38A F.3.13/F.3.15/F.3.17 -- CFB128 encryption, all key sizes.

    CFB128 is the one segment size where the RTL's LSB-first segment ordering
    and the standard's byte-stream ordering coincide (the segment is the whole
    block), so the published vectors apply directly.
    """
    banner(dut, "TC24: SP 800-38A F.3 CFB128 encryption")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_CFB128.items():
        await reset_dut(dut)
        cfg = AesConfig("CFB", bytes.fromhex(key_hex), cfb_seg_bits=128)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, PT_38A)
        iv = res.enc_cntxt_out
        if iv == IV_38A:
            compare(dut, cfg, res.outputs, rtl_blocks(ct_hex), context=iv,
                    label=f"TC24 CFB128-{bits}")
        else:
            # The DUT generates its own IV, so score against the model seeded
            # with the IV it reported; the published vector then only pins the
            # model, which TC0 already did.
            compare(dut, cfg, res.outputs,
                    cfg.model().cfb_encrypt(PT_38A, iv, 128), context=iv,
                    label=f"TC24 CFB128-{bits}")
        dut._log.info(f"  AES-{bits}: 4/4 blocks match (IV {rtl_hex(iv)})")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb_outvalid_waits_for_final_segment(dut):
    """CFB must not assert outVALID until the last segment has been computed.

    aes.sv:577 raises outVALID whenever `seg_cntr == seg_cntr_lim`, with no
    `cipher_done` term. Two consequences:

      * CFB128 (cfb_seg_bits = 3'b101) is not listed in the seg_cntr_lim case at
        aes.sv:284-291, so it takes `default: 4'h0`. seg_cntr is also 0 on entry
        to SHOOT, so the condition is true on the very first cycle and outVALID
        rises before a single cipher run has finished. The `else if` at
        aes.sv:578 that was written to handle CFB128 can never be reached.
      * For s < 128 the same condition is true on entry to the *final* segment,
        so outVALID rises one whole cipher run before that segment's result is
        merged into output_block.

    Counting completed cipher runs before outVALID rises measures this directly:
    it must be 128/s, not 128/s - 1 and not 0.
    """
    banner(dut, "TC24b: outVALID must wait for the final CFB segment")
    env = await bringup(dut)
    done = probe(dut, "AES.cipher_done")
    if done is None:
        dut._log.warning("  AES.cipher_done not visible -- skipping")
        return

    failures = []
    for s in (128, 64, 32, 16):
        await reset_dut(dut)
        cfg = AesConfig("CFB", KEY_128, cfb_seg_bits=s)
        apply_config(dut, cfg)
        await send_block(dut, PT_38A[0], first=True)

        runs, prev = 0, int(done.value)
        for _ in range(BLOCK_TIMEOUT):
            await FallingEdge(dut.clk)
            cur = int(done.value)
            if cur and not prev:
                runs += 1
            prev = cur
            if int(dut.outVALID.value):
                break
        want_runs = 128 // s
        dut._log.info(f"  CFB{s}: {runs} cipher run(s) completed before outVALID, "
                      f"expected {want_runs}")
        if runs != want_runs:
            failures.append(f"CFB{s}: outVALID after {runs} cipher runs, "
                            f"expected {want_runs}")
        dut.outREADY.value = 1
        await RisingEdge(dut.clk)
        dut.outREADY.value = 0

    assert not failures, (
        "outVALID is asserted before the block is complete:\n  "
        + "\n  ".join(failures)
        + "\n  aes.sv:577 tests `seg_cntr == seg_cntr_lim` with no cipher_done "
          "term. Add it (and give CFB128 its own seg_cntr_lim entry, or handle "
          "3'b101 before the equality test), or every CFB block is handed to the "
          "consumer with its last segment missing")


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb128_decrypt_sp80038a(dut):
    """SP 800-38A F.3.14/F.3.16/F.3.18 -- CFB128 decryption with a supplied IV.

    CFB decryption uses the forward cipher too, so a failure here is a feedback
    routing problem, not a datapath one.
    """
    banner(dut, "TC25: SP 800-38A F.3 CFB128 decryption")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_CFB128.items():
        await reset_dut(dut)
        cfg = AesConfig("CFB", bytes.fromhex(key_hex), decrypt=True, cfb_seg_bits=128)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, rtl_blocks(ct_hex), enc_cntxt_in=IV_38A)
        compare(dut, cfg, res.outputs, PT_38A, context=IV_38A,
                label=f"TC25 CFB128-{bits} decrypt")
        dut._log.info(f"  AES-{bits}: 4/4 blocks match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb_decrypt_feedback_source(dut):
    """CFB decryption must feed back the CIPHERTEXT, not what it just produced.

    aes.sv:520-528 builds the next shift-register value from
    `aesBus.output_block` unconditionally, for every segment size. On the
    encryption path output_block holds the ciphertext, which is correct. On the
    decryption path it holds the *plaintext*, so the register diverges from the
    one the encryptor used after the very first segment and every later segment
    decrypts to garbage. The check is deliberately a single 128-bit block per
    segment size, so a CFB128 failure cannot be blamed on segment bookkeeping.
    """
    banner(dut, "TC26: CFB decryption feedback register source")
    env = await bringup(dut)
    key = KEY_128
    m = AesModeModel(key)
    rng = random.Random(0xCFBFEED)
    pt = [rng.getrandbits(128)]
    for s in (128, 64, 32, 16, 8):
        ct = m.cfb_encrypt(pt, IV_38A, s)
        await reset_dut(dut)
        cfg = AesConfig("CFB", key, decrypt=True, cfb_seg_bits=s)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, ct, enc_cntxt_in=IV_38A)
        assert res.outputs[0] == pt[0], (
            f"CFB{s} decryption returned {rtl_hex(res.outputs[0])}, "
            f"want {rtl_hex(pt[0])}.\n"
            f"  aes.sv:520-528 feeds `output_block` back into cipherIn "
            f"regardless of mode[3]. Decrypting, output_block is the recovered "
            f"PLAINTEXT segment, but CFB's shift register must take the "
            f"CIPHERTEXT segment (the input) or it cannot track the encryptor's "
            f"register. The feedback source has to be selected on mode[3]")
        dut._log.info(f"  CFB{s}: decryption inverts encryption")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb_segment_roundtrip(dut):
    """Every CFB segment size round-trips a multi-block message.

    CFB8 runs 16 cipher invocations per 128-bit block, CFB64 two, so this also
    exercises the `seg_cntr` bookkeeping and the mid-block ARM/SHOOT loop that
    the other modes never enter.
    """
    banner(dut, "TC27: CFB8/16/32/64/128 round trip")
    env = await bringup(dut)
    rng = random.Random(0x5E65)
    key = KEY_128
    for s in (128, 64, 32, 16, 8):
        blocks = rand_blocks(rng, 2)
        await reset_dut(dut)
        enc = AesConfig("CFB", key, cfb_seg_bits=s)
        apply_config(dut, enc)
        res = await run_message(dut, enc, blocks)
        iv = res.enc_cntxt_out
        compare(dut, enc, res.outputs, enc.model().cfb_encrypt(blocks, iv, s),
                context=iv, label=f"TC27 CFB{s} encrypt")

        await reset_dut(dut)
        dec = AesConfig("CFB", key, decrypt=True, cfb_seg_bits=s)
        apply_config(dut, dec)
        back = await run_message(dut, dec, res.outputs, enc_cntxt_in=iv)
        compare(dut, dec, back.outputs, blocks, context=iv,
                label=f"TC27 CFB{s} round trip")
        dut._log.info(f"  CFB{s}: {len(blocks)} blocks round-tripped")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb_segment_counter_restart(dut):
    """Abandoning a CFB message mid-block and restarting with `first` recovers.

    `seg_cntr` is mode-internal bookkeeping the interface knows nothing about.
    aes.sv:512 clears it unconditionally on `first`, which is the whole reason
    the Case-1 contract was adopted (see the interface comment at aes.sv:81-88).
    This aborts a CFB8 block after a few segments, then starts a fresh message.
    """
    banner(dut, "TC28: CFB message aborted mid-block, then restarted")
    env = await bringup(dut)
    key = KEY_128
    cfg = AesConfig("CFB", key, cfb_seg_bits=8)
    apply_config(dut, cfg)

    await send_block(dut, PT_38A[0], first=True)
    await ClockCycles(dut.clk, 900)           # a few segments in, then abandon
    seg = probe(dut, "AES.seg_cntr")
    if seg is not None:
        dut._log.info(f"  abandoning with seg_cntr = {int(seg.value)}")

    blocks = [PT_38A[1]]
    res = await run_message(dut, cfg, blocks)
    iv = res.enc_cntxt_out
    compare(dut, cfg, res.outputs, cfg.model().cfb_encrypt(blocks, iv, 8),
            context=iv, label="TC28 CFB8 restart")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def cfb_input_capture_is_gated(dut):
    """A streaming sender must not corrupt the CFB block already in flight.

    aes.sv:505 captures `temp <= input_block` on `inVALID` alone, not on
    `inVALID && inREADY`. CFB re-enters ARM between every segment with
    `inREADY` deasserted (aes.sv:502), so a sender that keeps `inVALID` high --
    perfectly legal, it is waiting for READY -- overwrites the block being
    segmented. This presents the next block early and checks the first one still
    comes out right.
    """
    banner(dut, "TC29: input capture must be gated on inREADY, not inVALID alone")
    env = await bringup(dut)
    key = KEY_128
    cfg = AesConfig("CFB", key, cfb_seg_bits=16)
    apply_config(dut, cfg)

    # Accept block 0 normally.
    await send_block(dut, PT_38A[0], first=True)
    # Immediately present block 1 and hold it, as a streaming sender would while
    # waiting for inREADY. inREADY is low for the whole of block 0's segments.
    dut.input_block.value = PT_38A[1]
    dut.inVALID.value = 1
    out0 = await recv_block(dut)
    dut.inVALID.value = 0

    iv = out0.enc_cntxt_out
    want = cfg.model().cfb_encrypt([PT_38A[0]], iv, 16)[0]
    assert out0.data == want, (
        f"CFB16 block 0 = {rtl_hex(out0.data)}, want {rtl_hex(want)}.\n"
        f"  The next block was presented on input_block while inREADY was low. "
        f"aes.sv:505 latches `temp` on inVALID alone, so the block being "
        f"segmented was replaced mid-flight. The capture must be qualified with "
        f"inREADY -- a sender holding VALID until READY is the normal case, not "
        f"a protocol violation")
    env.checker.check()


# ===========================================================================
# TC30..TC34 -- OFB
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ofb_sp80038a(dut):
    """SP 800-38A F.4 -- OFB in both directions, all three key sizes.

    OFB is a pure keystream mode, so encryption and decryption are the same
    operation; both are driven here so a direction-dependent bug cannot hide.
    """
    banner(dut, "TC30: SP 800-38A F.4 OFB, both directions")
    env = await bringup(dut)
    for bits, (key_hex, ct_hex) in SP800_38A_OFB.items():
        key = bytes.fromhex(key_hex)
        ct = rtl_blocks(ct_hex)

        await reset_dut(dut)
        dec = AesConfig("OFB", key, decrypt=True)
        apply_config(dut, dec)
        res = await run_message(dut, dec, ct, enc_cntxt_in=IV_38A)
        compare(dut, dec, res.outputs, PT_38A, context=IV_38A,
                label=f"TC30 OFB-{bits} decrypt")

        await reset_dut(dut)
        enc = AesConfig("OFB", key)
        apply_config(dut, enc)
        res2 = await run_message(dut, enc, PT_38A)
        iv = res2.enc_cntxt_out
        compare(dut, enc, res2.outputs, enc.model().ofb(PT_38A, iv), context=iv,
                label=f"TC30 OFB-{bits} encrypt")
        dut._log.info(f"  AES-{bits}: both directions match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ofb_keystream_is_cipher_output(dut):
    """OFB feeds back O(j-1), the raw cipher output -- not C(j-1).

    Feeding back the ciphertext instead would silently turn OFB into CFB128.
    The two agree on block 0 and diverge from block 1, so the test scores a
    multi-block message against both models and requires OFB to win.
    """
    banner(dut, "TC31: OFB feedback is the cipher output, not the ciphertext")
    env = await bringup(dut)
    cfg = AesConfig("OFB", KEY_128)
    apply_config(dut, cfg)
    res = await run_message(dut, cfg, PT_38A)
    iv = res.enc_cntxt_out
    m = cfg.model()
    as_ofb = m.ofb(PT_38A, iv)
    as_cfb128 = m.cfb_encrypt(PT_38A, iv, 128)
    assert as_ofb != as_cfb128, "test is vacuous: the two models agree"
    if res.outputs == as_cfb128:
        raise AssertionError(
            "OFB output matches the CFB128 model exactly -- the feedback path is "
            "taking the ciphertext (output_block) instead of the raw cipher "
            "output. OFB requires I(j) = O(j-1) (SP 800-38A 6.4)")
    compare(dut, cfg, res.outputs, as_ofb, context=iv, label="TC31 OFB feedback")
    dut._log.info(f"  keystream feedback confirmed (IV {rtl_hex(iv)})")
    env.checker.check()


async def check_partial_masking(dut, mode, valid_bits_list, label):
    """Shared body for the OFB and CTR partial-final-block tests.

    `partial` and `valid_bits` are read in the SHOOT state (aes.sv:636-637 for
    OFB, 685-686 for CTR), i.e. after `inREADY` has been seen and a Case-1
    sender has already released them. Each width is therefore run twice: once
    with the discipline aes.sv:81-88 actually promises, and once holding the
    sideband all the way to `outVALID`. If the second passes where the first
    failed, the masking depends on a hold the interface does not require, and
    the failure message says so instead of leaving it as a bare mismatch.
    """
    results = []
    for valid_bits in valid_bits_list:
        await reset_dut(dut)
        cfg1 = AesConfig(mode, KEY_128, hold=HoldStyle.CASE1)
        apply_config(dut, cfg1)
        r1 = await run_message(dut, cfg1, PT_38A[:2], partial_bits=valid_bits)
        ctx1 = r1.enc_cntxt_out
        want1 = expected_outputs(cfg1, PT_38A[:2], ctx1, partial_bits=valid_bits)
        ok_case1 = r1.outputs == want1

        await reset_dut(dut)
        cfg2 = AesConfig(mode, KEY_128, hold=HoldStyle.THROUGH_OUTPUT)
        apply_config(dut, cfg2)
        r2 = await run_message(dut, cfg2, PT_38A[:2], partial_bits=valid_bits)
        ctx2 = r2.enc_cntxt_out
        want2 = expected_outputs(cfg2, PT_38A[:2], ctx2, partial_bits=valid_bits)
        ok_case2 = r2.outputs == want2

        results.append((valid_bits, ok_case1, ok_case2))
        dut._log.info(f"  valid_bits={valid_bits:3d}: "
                      f"Case-1 hold {'OK ' if ok_case1 else 'BAD'}   "
                      f"held-to-outVALID {'OK ' if ok_case2 else 'BAD'}")
        if not ok_case1:
            dut._log.warning(f"    Case-1 final block got  "
                             f"{rtl_hex(r1.outputs[-1])}")
            dut._log.warning(f"    Case-1 final block want {rtl_hex(want1[-1])}")

    broken = [v for v, c1, _ in results if not c1]
    needs_hold = [v for v, c1, c2 in results if not c1 and c2]
    assert not broken, (
        f"{label}: partial masking failed for valid_bits={broken} under the "
        f"Case-1 hold discipline.\n"
        f"  Widths that then worked when the sideband was held to outVALID: "
        f"{needs_hold or 'none'}.\n"
        f"  aes.sv reads `partial`/`valid_bits` combinationally in SHOOT, but "
        f"aes.sv:81-88 lets the sender release every input-channel signal as "
        f"soon as inREADY is seen. Both must be latched at the input handshake "
        f"and the latched copies used in SHOOT -- the same fix `first` needs on "
        f"the CBC decrypt path (TC21)")


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ofb_partial_final_block(dut):
    """A partial final OFB block keeps its top `valid_bits` bits and zeroes the rest.

    aes.sv:637 masks with `{128{1'b1}} << (~valid_bits + 7'd1)`, which is 7-bit
    two's complement for 128-valid_bits. Each width is run under both hold
    disciplines so a failure identifies whether the masking logic or the signal
    timing is at fault.
    """
    banner(dut, "TC32: OFB partial final block masking")
    env = await bringup(dut)
    await check_partial_masking(dut, "OFB", (1, 8, 63, 64, 100, 127), "TC32 OFB")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ofb_roundtrip(dut):
    """OFB encrypt then decrypt with the reported IV recovers the plaintext."""
    banner(dut, "TC33: OFB round trip")
    env = await bringup(dut)
    rng = random.Random(0x0FB17)
    blocks = rand_blocks(rng, 3)
    for bits, key in KEYS.items():
        await reset_dut(dut)
        enc = AesConfig("OFB", key)
        apply_config(dut, enc)
        res = await run_message(dut, enc, blocks)
        iv = res.enc_cntxt_out

        await reset_dut(dut)
        dec = AesConfig("OFB", key, decrypt=True)
        apply_config(dut, dec)
        back = await run_message(dut, dec, res.outputs, enc_cntxt_in=iv)
        compare(dut, dec, back.outputs, blocks, context=iv,
                label=f"TC33 OFB-{bits} round trip")
        dut._log.info(f"  AES-{bits}: round trip OK")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ofb_iv_context_direction(dut):
    """encCntxtOut carries the IV when encrypting and is suppressed when decrypting.

    aes.sv:613 zeroes it on the decrypt path. A decrypting instance echoing back
    an IV-shaped value invites an integrator to store and reuse it.
    """
    banner(dut, "TC34: encCntxtOut direction discipline in OFB")
    env = await bringup(dut)
    key = KEY_128
    enc = AesConfig("OFB", key)
    apply_config(dut, enc)
    res = await run_message(dut, enc, PT_38A[:1])
    assert res.enc_cntxt_out != 0, "OFB encryption reported a zero IV"

    await reset_dut(dut)
    dec = AesConfig("OFB", key, decrypt=True)
    apply_config(dut, dec)
    res2 = await run_message(dut, dec, PT_38A[:1], enc_cntxt_in=IV_38A)
    assert res2.enc_cntxt_out == 0, (
        f"OFB decryption reported encCntxtOut = {rtl_hex(res2.enc_cntxt_out)}; "
        f"aes.sv:613 suppresses it on the decrypt path so a peer cannot mistake "
        f"it for a freshly generated IV")
    env.checker.check()


# ===========================================================================
# TC35..TC40 -- CTR
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_counter_successor(dut):
    """Establish which counter successor function CTR actually implements.

    aes.sv:682 does `ctr_mode_cntr + 1` on a register that is in state-matrix
    bit order, so +1 lands in NIST byte 3, not byte 15. SP 800-38A B.1's
    standard incrementing function increments the counter block in its natural
    byte order. Both keep counters unique, but only one interoperates with a
    standard CTR peer given nothing but `encCntxtOut`.
    """
    banner(dut, "TC35: CTR counter successor function")
    env = await bringup(dut)
    cfg = AesConfig("CTR", KEY_128)
    apply_config(dut, cfg)
    res = await run_message(dut, cfg, PT_38A)
    c0 = res.enc_cntxt_out
    m = cfg.model()
    as_rtl = m.ctr(PT_38A, c0, increment="rtl")
    as_nist = m.ctr(PT_38A, c0, increment="nist")

    if res.outputs == as_nist:
        dut._log.info("  DUT uses the SP 800-38A standard incrementing function")
    elif res.outputs == as_rtl:
        raise AssertionError(
            "CTR increments the counter in state-matrix bit order, not in "
            "counter-block byte order.\n"
            f"  {M.CTR_INCREMENT_NOTE}\n"
            f"  counter[0] reported as {rtl_hex(c0)}; the DUT's counter[1] is "
            f"{rtl_hex(m.ctr_next_rtl(c0))} where SP 800-38A B.1 requires "
            f"{rtl_hex(m.ctr_next_nist(c0))}")
    else:
        compare(dut, cfg, res.outputs, as_nist, context=c0,
                label="TC35 CTR (neither successor matches)")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_roundtrip(dut):
    """CTR encrypt then decrypt with the reported counter recovers the plaintext.

    Scored against whichever successor the DUT uses, so this stays a statement
    about the mode plumbing even if TC35 has already flagged the increment.
    """
    banner(dut, "TC36: CTR round trip")
    env = await bringup(dut)
    rng = random.Random(0xC7217)
    blocks = rand_blocks(rng, 3)
    for bits, key in KEYS.items():
        await reset_dut(dut)
        enc = AesConfig("CTR", key)
        apply_config(dut, enc)
        res = await run_message(dut, enc, blocks)
        c0 = res.enc_cntxt_out

        await reset_dut(dut)
        dec = AesConfig("CTR", key, decrypt=True)
        apply_config(dut, dec)
        back = await run_message(dut, dec, res.outputs, enc_cntxt_in=c0)
        compare(dut, dec, back.outputs, blocks, context=c0,
                label=f"TC36 CTR-{bits} round trip")
        dut._log.info(f"  AES-{bits}: round trip OK (counter0 {rtl_hex(c0)})")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_counter_never_repeats(dut):
    """No counter value is ever reused across messages under one key.

    This is CTR's only security requirement, and the reason the counter was
    designed as a free-running register seeded once rather than reloaded per
    message. Reusing a counter is a two-time pad.
    """
    banner(dut, "TC37: CTR counter uniqueness across messages")
    env = await bringup(dut)
    cfg = AesConfig("CTR", KEY_128)
    apply_config(dut, cfg)
    seen, starts = set(), []
    n_msgs, n_blocks = 5, 3
    for i in range(n_msgs):
        res = await run_message(dut, cfg, PT_38A[:n_blocks])
        c0 = res.enc_cntxt_out
        starts.append(c0)
        used = cfg.model().ctr_sequence(n_blocks, c0)
        for c in used:
            assert c not in seen, (
                f"counter {rtl_hex(c)} reused in message {i}. Every block "
                f"encrypted under a repeated counter is a two-time pad against "
                f"the earlier one; counter starts so far: "
                f"{[rtl_hex(s) for s in starts]}")
            seen.add(c)
        dut._log.info(f"  message {i}: counter0 = {rtl_hex(c0)}")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_counter_survives_mode_switch(dut):
    """Leaving CTR and coming back does not restart the counter.

    Every other mode's branch zeroes the registers it does not use; the CTR
    counter deliberately is not one of them (that fix is recorded in the design
    notes). If an ECB message in between resets it, the next CTR message
    replays counters already used under the same key.
    """
    banner(dut, "TC38: CTR counter survives an excursion through another mode")
    env = await bringup(dut)
    ctr = AesConfig("CTR", KEY_128)
    ecb = AesConfig("ECB", KEY_128)

    apply_config(dut, ctr)
    first = await run_message(dut, ctr, PT_38A[:2])
    c_before = first.enc_cntxt_out

    apply_config(dut, ecb)
    await run_message(dut, ecb, PT_38A[:1])

    apply_config(dut, ctr)
    second = await run_message(dut, ctr, PT_38A[:2])
    c_after = second.enc_cntxt_out

    used_before = set(ctr.model().ctr_sequence(2, c_before))
    used_after = set(ctr.model().ctr_sequence(2, c_after))
    dut._log.info(f"  counter0 before = {rtl_hex(c_before)}, "
                  f"after = {rtl_hex(c_after)}")
    assert not (used_before & used_after), (
        f"the CTR counter restarted across a mode excursion: message 1 used "
        f"{[rtl_hex(c) for c in sorted(used_before)]} and message 2 reused "
        f"{[rtl_hex(c) for c in sorted(used_before & used_after)]}. "
        f"ctr_mode_cntr must not be cleared while another mode is selected")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_decrypt_preserves_encrypt_counter(dut):
    """A CTR decryption must not disturb the live encryption counter.

    Decryption replays an externally supplied counter. If that load lands in the
    same register the encryption side is counting in, running a decrypt rewinds
    the encryptor and the next encryption reuses counter values -- reachable
    without ever leaving CTR mode.
    """
    banner(dut, "TC39: CTR decryption must not clobber the encryption counter")
    env = await bringup(dut)
    enc = AesConfig("CTR", KEY_128)
    dec = AesConfig("CTR", KEY_128, decrypt=True)

    apply_config(dut, enc)
    m1 = await run_message(dut, enc, PT_38A[:2])
    used1 = set(enc.model().ctr_sequence(2, m1.enc_cntxt_out))

    # Decrypt something with a counter far away from the live one.
    apply_config(dut, dec)
    await run_message(dut, dec, PT_38A[:2], enc_cntxt_in=CTR0_38A)

    apply_config(dut, enc)
    m2 = await run_message(dut, enc, PT_38A[:2])
    used2 = set(enc.model().ctr_sequence(2, m2.enc_cntxt_out))

    dut._log.info(f"  before decrypt: counter0 = {rtl_hex(m1.enc_cntxt_out)}")
    dut._log.info(f"  after  decrypt: counter0 = {rtl_hex(m2.enc_cntxt_out)}")
    assert not (used1 & used2), (
        f"running a CTR decryption rewound the encryption counter: "
        f"{[rtl_hex(c) for c in sorted(used1 & used2)]} were used by both "
        f"encryptions. The decrypt-side replay counter must live in its own "
        f"register")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def ctr_partial_final_block(dut):
    """A partial final CTR block keeps its top `valid_bits` bits.

    Same masking path as OFB (aes.sv:686) but reached through the CTR branch,
    which computes its keystream from the counter rather than from feedback.
    """
    banner(dut, "TC40: CTR partial final block masking")
    env = await bringup(dut)
    await check_partial_masking(dut, "CTR", (1, 32, 64, 127), "TC40 CTR")
    env.checker.check()


# ===========================================================================
# TC41..TC46 -- Handshake and protocol
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def output_backpressure(dut):
    """The output block survives arbitrary consumer backpressure.

    outVALID must stay asserted and output_block/encCntxtOut must not move while
    outREADY is withheld -- policed every cycle by ProtocolChecker as well as
    checked here at the transfer point.
    """
    banner(dut, "TC41: output-channel backpressure")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    want = cfg.model().ecb_encrypt(PT_38A)
    for delay in (0, 1, 5, 37, 200):
        await reset_dut(dut)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, PT_38A, ready_delay=delay)
        compare(dut, cfg, res.outputs, want, label=f"TC41 ready_delay={delay}")
        dut._log.info(f"  outREADY delayed {delay} cycles: 4/4 blocks intact")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def input_capture_requires_inready(dut):
    """The DUT must not latch input_block on a cycle where inREADY is low.

    aes.sv captures with `cipherIn <= (inVALID) ? input_block : cipherIn` and
    asserts `inREADY <= 1` on the same edge, so the transfer is taken on a cycle
    where a VALID/READY master still sees READY low. This watches the internal
    capture register and the handshake together and reports the ordering.
    """
    banner(dut, "TC42: input capture vs inREADY ordering")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    cin = probe(dut, "AES.cipherIn")
    if cin is None:
        dut._log.warning("  AES.cipherIn not visible -- skipping the internal check")
        return

    dut.input_block.value = PT_38A[0]
    dut.first.value = 1
    dut.inVALID.value = 1
    captured_at = None
    ready_at = None
    for cyc in range(200):
        await RisingEdge(dut.clk)
        if captured_at is None and int(cin.value) == PT_38A[0]:
            captured_at = cyc
        if ready_at is None and int(dut.inREADY.value):
            ready_at = cyc
        if captured_at is not None and ready_at is not None:
            break
    dut.inVALID.value = 0
    dut._log.info(f"  input latched on cycle {captured_at}, "
                  f"inREADY first high on cycle {ready_at}")
    assert captured_at is not None, "input_block was never captured"
    assert ready_at is not None and ready_at <= captured_at, (
        f"input_block was latched on cycle {captured_at} but inREADY did not go "
        f"high until cycle {ready_at}. The DUT consumed a block on a cycle where "
        f"a VALID/READY master had not yet been granted the transfer, so a "
        f"master that changes its data on the next edge (which it is entitled to "
        f"do once it does see READY) can have the wrong block encrypted")
    await recv_block(dut)
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def sender_idle_gaps(dut):
    """Idle cycles between blocks change nothing.

    A sender that is not continuously ready is the normal case in an SoC. The
    DUT must sit in ARM with inREADY asserted and pick up exactly where it left
    off, with no spurious capture of the parked (zero) input bus.
    """
    banner(dut, "TC43: idle gaps between input blocks")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    want = cfg.model().ecb_encrypt(PT_38A)
    for gap in (0, 1, 3, 17, 150):
        await reset_dut(dut)
        apply_config(dut, cfg)
        res = await run_message(dut, cfg, PT_38A, send_gap=gap)
        compare(dut, cfg, res.outputs, want, label=f"TC43 send_gap={gap}")
        dut._log.info(f"  {gap}-cycle sender gap: 4/4 blocks intact")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def randomized_handshake_stress(dut):
    """A long message under randomized VALID/READY timing.

    Randomizes the sender's gap and the consumer's backpressure independently on
    every block, which is where a handshake bug that survives fixed timing shows
    up. Deterministically seeded so a failure is reproducible.
    """
    banner(dut, "TC44: randomized handshake timing")
    env = await bringup(dut)
    rng = random.Random(0x4A5DEAD)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    blocks = rand_blocks(rng, 12)
    want = cfg.model().ecb_encrypt(blocks)
    got = []
    for i, blk in enumerate(blocks):
        gap = rng.choice([0, 0, 1, 2, 5, 11])
        delay = rng.choice([0, 0, 1, 3, 9, 40])
        if gap:
            await ClockCycles(dut.clk, gap)
        await send_block(dut, blk, first=(i == 0))
        got.append((await recv_block(dut, ready_delay=delay)).data)
    compare(dut, cfg, got, want, label="TC44 randomized timing")
    dut._log.info(f"  {len(blocks)} blocks under randomized timing: all match")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def max_throughput_stream(dut):
    """Back-to-back blocks with outREADY parked high the whole time.

    The zero-idle case: the consumer never backpressures and the sender presents
    the next block the instant the previous is accepted. Also records the
    per-block cycle cost, which is the number a system integrator needs.
    """
    banner(dut, "TC45: maximum-throughput streaming")
    env = await bringup(dut)
    cfg = AesConfig("ECB", KEY_128)
    apply_config(dut, cfg)
    blocks = PT_38A * 2
    want = cfg.model().ecb_encrypt(blocks)
    got, costs = [], []
    for i, blk in enumerate(blocks):
        c0 = await send_block(dut, blk, first=(i == 0))
        r = await recv_block(dut)
        got.append(r.data)
        costs.append(c0 + r.cycles)
    compare(dut, cfg, got, want, label="TC45 max throughput")
    dut._log.info(f"  per-block cycles: {costs}")
    dut._log.info(f"  steady state ~{sum(costs[1:]) // max(1, len(costs) - 1)} "
                  f"cycles/block after the first")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def outvalid_not_asserted_without_input(dut):
    """The DUT never produces an output it was not given an input for.

    Sits configured and idle with outREADY high for a long window and requires
    outVALID to stay low. A spontaneous outVALID means the FSM can leave ARM
    without a handshake -- and in CBC/CFB/OFB it would also burn an IV.
    """
    banner(dut, "TC46: no output without an accepted input")
    env = await bringup(dut)
    for mode in ("ECB", "CBC", "CFB", "OFB", "CTR"):
        await reset_dut(dut)
        cfg = AesConfig(mode, KEY_128)
        apply_config(dut, cfg)
        dut.outREADY.value = 1
        for _ in range(2000):
            await FallingEdge(dut.clk)
            assert int(dut.outVALID.value) == 0, (
                f"{mode}: outVALID asserted with no input block ever accepted. "
                f"{dut_state(dut)}")
        dut.outREADY.value = 0
        dut._log.info(f"  {mode}: idle for 2000 cycles, no spurious output")
    env.checker.check()


# ===========================================================================
# TC47..TC49 -- Entropy and IV subsystem
# ===========================================================================
@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def iv_generation_latency(dut):
    """The first IV arrives within the documented pipeline budget, and is consumed.

    iv_gen must condition a 384-bit seed (~1200 clk) and run CTR_DRBG
    Instantiate plus one Generate (~260 clk) before the first CBC block can
    start. This measures it and confirms the AES actually handshakes the IV
    (`aes_iv_ready`) rather than free-running on a stale value.
    """
    banner(dut, "TC47: first-IV latency and handshake")
    env = await bringup(dut)
    cfg = AesConfig("CBC", KEY_128)
    apply_config(dut, cfg)

    iv_ready = probe(dut, "AES.aes_iv_ready")
    saw_ready = False
    if iv_ready is not None:
        async def watch():
            nonlocal saw_ready
            while True:
                await FallingEdge(dut.clk)
                if int(iv_ready.value):
                    saw_ready = True
        cocotb.start_soon(watch())

    cycles = await send_block(dut, PT_38A[0], first=True)
    res = await recv_block(dut)
    dut._log.info(f"  first CBC block accepted after {cycles} cycles, "
                  f"IV = {rtl_hex(res.enc_cntxt_out)}")
    assert cycles < IV_TIMEOUT, f"first IV took {cycles} cycles"
    if iv_ready is not None:
        assert saw_ready, (
            "aes_iv_ready never asserted -- the AES took an IV without "
            "completing iv_gen's VALID/READY handshake, so CTR_DRBG was never "
            "told to advance and the next message would reuse this IV")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def iv_not_requested_in_ecb_and_ctr(dut):
    """ECB and CTR never assert aes_iv_ready.

    Neither mode needs a generated IV (aes.sv:379, 700). Consuming one anyway
    would burn DRBG output and, worse, make ECB's timing depend on the entropy
    pipeline.
    """
    banner(dut, "TC48: no IV consumed in ECB or CTR")
    env = await bringup(dut)
    iv_ready = probe(dut, "AES.aes_iv_ready")
    if iv_ready is None:
        dut._log.warning("  AES.aes_iv_ready not visible -- skipping")
        return
    for mode in ("ECB", "CTR"):
        await reset_dut(dut)
        cfg = AesConfig(mode, KEY_128)
        apply_config(dut, cfg)
        violations = []

        async def watch():
            while True:
                await FallingEdge(dut.clk)
                if int(iv_ready.value):
                    violations.append(1)
        t = cocotb.start_soon(watch())
        await run_message(dut, cfg, PT_38A[:2])
        t.cancel()
        assert not violations, (
            f"{mode} asserted aes_iv_ready {len(violations)} times -- it "
            f"consumed IVs from CTR_DRBG that it has no use for")
        dut._log.info(f"  {mode}: aes_iv_ready never asserted")
    env.checker.check()


@cocotb.test(timeout_time=TIMEOUT_MS, timeout_unit="ms")
async def entropy_failure_does_not_hang_silently(dut):
    """A stuck noise source must not leave the AES waiting forever with no signal.

    Forcing raw_rand_bit_cbc_mac to a constant trips the Repetition Count Test
    inside cbc_mac, which drives iv_gen's CTR_DRBG to UNINSTANTIATE. A CBC
    encryption blocked on `iv_valid` then stalls. There is no status output on
    `aes_interface` for this, so the stall is indistinguishable from a slow IV --
    which is the finding this test records.
    """
    banner(dut, "TC49: entropy failure while a CBC message is waiting for an IV")
    env = await bringup(dut)
    env.set_cbcmac_noise("stuck_1")
    cfg = AesConfig("CBC", KEY_128)
    apply_config(dut, cfg)

    dut.input_block.value = PT_38A[0]
    dut.first.value = 1
    dut.inVALID.value = 1
    accepted = False
    for _ in range(20000):
        await FallingEdge(dut.clk)
        if int(dut.inREADY.value):
            accepted = True
            break
    dut.inVALID.value = 0
    dut._log.info(f"  with a stuck noise source, block accepted = {accepted}")

    # Recover: healthy entropy plus a reset must bring the DUT back.
    env.set_cbcmac_noise("physics", offset=21000)
    await reset_dut(dut)
    apply_config(dut, cfg)
    await run_and_check(dut, cfg, PT_38A[:1], label="TC49 post-recovery CBC")
    dut._log.info("  recovered after reset with healthy entropy")
    assert not accepted, (
        "the AES accepted a CBC block while the entropy source was stuck and "
        "the health tests had failed. Either it used an IV derived from failed "
        "entropy, or iv_valid is not actually gating acceptance")
    env.checker.check()


# ===========================================================================
# TC50..TC52 -- Cross-mode and soak
# ===========================================================================
@cocotb.test(timeout_time=SOAK_TIMEOUT_MS, timeout_unit="ms")
async def all_mode_keysize_matrix(dut):
    """Every (mode, direction, key size) combination on a two-block message.

    The completeness sweep: 5 modes x 2 directions x 3 key sizes. Each cell is
    scored against the model with whatever context the DUT reported or was
    given, so one cell failing does not mask the rest.
    """
    banner(dut, "TC50: full mode x direction x key-size matrix")
    env = await bringup(dut)
    rng = random.Random(0x3A7819)
    failures = []
    for mode in ("ECB", "CBC", "CFB", "OFB", "CTR"):
        for decrypt in (False, True):
            for bits, key in KEYS.items():
                cfg = AesConfig(mode, key, decrypt=decrypt)
                blocks = rand_blocks(rng, 2)
                ctx = 0 if cfg.needs_generated_iv else IV_38A
                await reset_dut(dut)
                try:
                    await run_and_check(dut, cfg, blocks, context=ctx,
                                        label=f"TC50 {cfg}")
                    dut._log.info(f"  {cfg}: PASS")
                except AssertionError as e:
                    failures.append(f"{cfg}: {str(e).splitlines()[0]}")
                    dut._log.error(f"  {cfg}: FAIL")
    assert not failures, (
        f"{len(failures)} of 30 mode/direction/key-size cells failed:\n  "
        + "\n  ".join(failures))
    env.checker.check()


@cocotb.test(timeout_time=SOAK_TIMEOUT_MS, timeout_unit="ms")
async def interleaved_mode_messages(dut):
    """Messages in different modes, interleaved, stay independent.

    A realistic driver multiplexes the block between users. Each message must
    depend only on its own blocks and its own context -- no carry-over of a
    chaining value, a segment counter or an IV from the message before it.
    """
    banner(dut, "TC51: interleaved messages across modes")
    env = await bringup(dut)
    rng = random.Random(0x1E7EA5)
    order = ["ECB", "CBC", "CTR", "OFB", "ECB", "CFB", "CBC", "CTR"]
    for i, mode in enumerate(order):
        cfg = AesConfig(mode, KEYS[rng.choice([128, 192, 256])],
                        cfb_seg_bits=128)
        blocks = rand_blocks(rng, 2)
        ctx = 0 if cfg.needs_generated_iv else IV_38A
        await run_and_check(dut, cfg, blocks, context=ctx,
                            label=f"TC51 msg{i} {cfg}")
        dut._log.info(f"  msg{i} {cfg}: OK")
    env.checker.check()


@cocotb.test(timeout_time=SOAK_TIMEOUT_MS, timeout_unit="ms")
async def long_random_soak(dut):
    """A long randomized stream: random mode, key, length and handshake timing.

    Everything the directed tests fix, this varies. The point is coverage of
    combinations nobody thought to enumerate, with a fixed seed so any failure
    is reproducible from the log.
    """
    banner(dut, "TC52: randomized soak")
    env = await bringup(dut)
    rng = random.Random(0x50A17)
    for msg in range(14):
        mode = rng.choice(["ECB", "CBC", "CFB", "OFB", "CTR"])
        decrypt = rng.random() < 0.5
        bits = rng.choice([128, 192, 256])
        seg = rng.choice([128, 64, 32]) if mode == "CFB" else 128
        cfg = AesConfig(mode, KEYS[bits], decrypt=decrypt, cfb_seg_bits=seg)
        blocks = rand_blocks(rng, rng.randint(1, 4))
        ctx = 0 if cfg.needs_generated_iv else rng.getrandbits(128)
        await reset_dut(dut)
        await run_and_check(dut, cfg, blocks, context=ctx,
                            ready_delay=rng.choice([0, 0, 2, 13]),
                            send_gap=rng.choice([0, 0, 1, 7]),
                            label=f"TC52 msg{msg} {cfg}")
        dut._log.info(f"  msg{msg}: {cfg} x{len(blocks)} OK")
    env.checker.check()
